CoARU_EMOTE = {
["A sly smirk spreads across your face."]="На вашем лице появляется хитрая усмешка.",
["A tendril of drool runs down your lip."]="С ваших губ стекает струйка слюны.",
["Blood oozes from your wounds."]="Ваши раны кровоточат.",
["In quiet contemplation, you mourn the loss of the dead."]="В глубоком молчании вы скорбите о павших.",
["Mooooooooooo."]="Муууууууууу!",
["With a finger deep in one nostril, you pass the time."]="Вы коротаете время, ковыряясь в носу.",
["With arms flapping, you strut around.  Cluck, Cluck, Chicken!"]="Хлопая руками, вы расхаживаете вокруг. Цыпа-цыпа-цыпа!",
["You OBJECT!"]="Вы ПРОТЕСТУЕТЕ!",
["You agree."]="Вы соглашаетесь.",
["You announce that you have low mana!"]="Вы заявляете, что у вас кончается мана!",
["You apologize to everyone.  Sorry!"]="Вы просите у всех прощения. Извините!",
["You applaud.  Bravo!"]="Вы аплодируете. Браво!",
["You are amazed!"]="Вы восхищены!",
["You are bashful."]="Вы краснеете.",
["You are filled with happiness!"]="Вас переполняет счастье!",
["You are filled with regret."]="Вас переполняет сожаление.",
["You are getting a headache."]="У вас болит голова.",
["You are hopelessly confused."]="Вы в полном недоумении.",
["You are hopelessly lost."]="Вы в полном недоумении.",
["You are hungry!"]="Вы голодны!",
["You are jealous of everyone around you."]="Вы завидуете всем вокруг.",
["You are listening!"]="Вы прислушиваетесь.",
["You are lost in thought."]="Вы погрузились в раздумья.",
["You are overcome with boredom.  Oh the drudgery!"]="Вы изнываете от скуки. Какое занудство!",
["You are proud of yourself."]="Вы гордитесь собой.",
["You are puzzled. What's going on here?"]="Вы озадачены. Что тут происходит?",
["You are scared!"]="Вы испуганы!",
["You are so surprised!"]="Вы так удивлены!",
["You are so thirsty. Can anyone spare a drink?"]="Вам так хочется пить. Никто не даст глоточек?",
["You are such a tease."]="Вы такая язва!",
["You are sweating."]="Вы покрываетесь потом.",
["You ask everyone to wait."]="Вы просите всех подождать.",
["You bare your teeth and snarl."]="Вы скалитесь и ворчите.",
["You bark. Woof woof!"]="Вы лаете. Гав-гав!",
["You bask in the glory of victory."]="Вы упиваетесь победой.",
["You beckon everyone over to you."]="Вы жестом подзываете всех к себе.",
["You beg everyone around you. How pathetic."]="Вы с мольбой смотрите на окружающих. Выглядит жалко.",
["You begin to eat."]="Вы начинаете есть.",
["You begin to groan."]="Вы начинаете стонать.",
["You begin to play the world's smallest violin."]="Вы начинаете играть на маленькой скрипочке.",
["You begin to work."]="Вы приступаете к работе.",
["You blame yourself for what happened."]="Вы заявляете, что вы во всем виноваты.",
["You blink your eyes."]="Вы моргаете.",
["You blow a kiss into the wind."]="Вы посылаете воздушный поцелуй.",
["You blush."]="Вы заливаетесь краской.",
["You boggle at the situation."]="Вы не знаете, что делать в этой ситуации.",
["You bonk yourself on the noggin.  Doh!"]="Вы стукаетесь головой. Буммм!",
["You bounce up and down."]="Вы подпрыгиваете на месте.",
["You bow down graciously."]="Вы изящно кланяетесь.",
["You brandish your weapon fiercely."]="Вы яростно размахиваете оружием.",
["You burst into dance."]="Вы пускаетесь в пляс.",
["You burst into song."]="Вы запеваете.",
["You cackle maniacally at the situation."]="Вы громко расхохотались.",
["You call out for healing!"]="Вы зовете лекаря!",
["You check your own pulse."]="Вы проверяете свой пульс. Никуда не делся.",
["You cheer!"]="Вы очень рады!",
["You clap excitedly."]="Вы восторженно апплодируете.",
["You clap half-heartedly, clearly unimpressed."]="Вы вяло аплодируете.",
["You clearly state, NO."]="Вы твердо заявляете: \"НЕТ!\"",
["You commend everyone on a job well done."]="Вы благодарите всех за хорошую работу.",
["You congratulate everyone around you."]="Вы поздравляете всех вокруг.",
["You cover your ears."]="Вы закрываете уши.",
["You cover your face with your palm."]="Вы прячете лицо в ладонях.",
["You cower in fear."]="Вы дрожите от страха.",
["You crack your knuckles."]="Вы похрустываете костяшками пальцев.",
["You cringe in fear."]="Вы сжимаетесь от страха.",
["You cross your arms."]="Вы скрещиваете руки.",
["You cross your eyes."]="У вас глаза лезут на лоб.",
["You cry out for help!"]="Вы зовете на помощь!",
["You cry."]="Вы плачете.",
["You curtsey."]="Вы делаете реверанс.",
["You dig through your backpack."]="Вы роетесь в своем рюкзаке.",
["You disagree."]="Вы не согласны.",
["You doubt the situation will end in your favor."]="Вы сомневаетесь, что ситуация разрешится в вашу пользу.",
["You drop to your knees and plead in desperation."]="Вы падаете на колени в отчаянной мольбе.",
["You drop your trousers and moon everyone."]="Вы снимаете штаны и показываете всем зад.",
["You duck for cover."]="Вы ищете укрытие.",
["You encourage everyone around you."]="Вы подбадриваете всех вокруг.",
["You express your curiosity to those around you."]="Вы показываете окружающим свое любопытство.",
["You faint."]="Вы падаете в обморок.",
["You fall asleep.  Zzzzzzz."]="Вы засыпаете. Хррррр...",
["You fart loudly.  Whew...what stinks?"]="Вы испускаете газы. Фууу...чем это воняет?",
["You feel the love."]="Вы чувствуете любовь.",
["You fidget."]="Вы нервничаете.",
["You flex your muscles.  Oooooh so strong!"]="Вы поигрываете мускулами. Вот это сила!",
["You flirt."]="Вы флиртуете.",
["You flop about helplessly."]="Вы беспомощно суетитесь.",
["You flush with embarrassment."]="Вы вспыхиваете от смущения.",
["You frown."]="Вы хмуритесь.",
["You gasp."]="Вы ахаете.",
["You gaze off into the distance."]="Вы смотрите куда-то вдаль.",
["You giggle."]="Вы хихикаете.",
["You give the order to open fire."]="Вы приказываете открыть огонь.",
["You give the signal."]="Вы подаете сигнал.",
["You glare angrily."]="Вы смотрите гневным взглядом.",
["You gloat over everyone's misfortune."]="Вы злорадствуете по поводу общей неудачи.",
["You glower at averyone around you."]="Вы зло смотрите на всех окружающих.",
["You greet everyone warmly."]="Вы тепло приветствуете всех вокруг.",
["You greet everyone with a hearty hello!"]="Вы от всего сердца приветствуете всех!",
["You grin wickedly."]="Вы злобно ухмыляетесь.",
["You grovel on the ground, wallowing in subservience."]="Вы ползаете на брюхе, выражая полную покорность.",
["You growl menacingly."]="Вы угрожающе рычите.",
["You hail those around you."]="Вы приветствуете всех.",
["You hang your head dejectedly."]="Вы уныло вешаете голову.",
["You have a bad feeling about this..."]="Вам кажется, что ничем хорошим это не закончится.",
["You have an idea!"]="У вас есть идея!",
["You have failed."]="Вы потерпели неудачу",
["You hiccup loudly."]="Вы громко икаете.",
["You hiss at everyone around you."]="Вы шипите на окружающих.",
["You introduce yourself to everyone."]="Вы представляетесь всем.",
["You kneel down."]="Вы преклоняете колени.",
["You laugh."]="Вы смеетесь.",
["You let everyone know that you are cold."]="Вы показываете всем, что вам холодно.",
["You let everyone know that you are ready!"]="Вы показываете всем, что готовы!",
["You let everyone know that you are tired."]="Вы показываете всем, что устали.",
["You let everyone know you'll be right back."]="Вы даете всем понять, что сейчас вернетесь.",
["You let forth a sharp whistle."]="Вы пронзительно свистите.",
["You let out a boisterous guffaw!"]="Вы громко гогочете!",
["You let out a hacking cough."]="Вы отрывисто кашляете.",
["You let out a hearty chuckle."]="Вы смеетесь от всей души.",
["You let out a long, drawn-out sigh."]="Вы испускаете долгий, усталый вздох.",
["You let out a loud belch."]="Вы громко рыгаете.",
["You lick your lips."]="Вы облизываетесь.",
["You lie down."]="Вы ложитесь.",
["You look absent-minded."]="Кажется, вы сбиты с толку.",
["You look around for someone to bite."]="Вы ищете, кого бы укусить.",
["You look around in awe."]="Вы оглядываетесь вокруг с благоговейным трепетом.",
["You look around nervously."]="Вы обеспокоено озираетесь по сторонам.",
["You look around."]="Вы смотрите по сторонам.",
["You make a rude gesture."]="Вы делаете неприличный жест.",
["You moan suggestively."]="Вы призывно стонете.",
["You mock life and all it stands for."]="Вы высмеиваете жизнь и все, что с ней связано.",
["You motion for everyone to follow."]="Вы жестом велите всем следовать за вами.",
["You must be going."]="Вам пора уходить.",
["You mutter angrily to yourself. Hmmmph!"]="Вы зло бормочите сбе под нос. Гхмммм!",
["You narrow your eyes in suspicion."]="Вы подозрительно щуритесь.",
["You need a hug!"]="Вы хотите, чтобы вас обняли.",
["You need a massage!"]="Вам нужен массаж!",
["You need a pat."]="Вы хотите, чтобы вас погладили.",
["You need to be comforted."]="Вы нуждаетесь в утешении.",
["You need to be cuddled."]="Вам хочется ласки.",
["You need to be petted."]="Вы нуждаетесь в ласке.",
["You need to be soothed."]="Вам нужно утешение.",
["You nod."]="Вы киваете.",
["You offer a truce."]="Вы предлагаете перемирие.",
["You peer around, searchingly."]="Вы внимательно осматриваетесь.",
["You pinch yourself."]="Вы щипаете себя.",
["You pity those around you."]="Вы жалеете окружающих.",
["You plead for mercy."]="Вы молите о пощаде.",
["You point over yonder."]="Вы показываете в ту сторону.",
["You poke your belly and giggle."]="Вы тыкаете себя в живот и хихикаете.",
["You ponder the situation."]="Вы обдумываете ситуацию.",
["You pounce out from the shadows."]="Вы выскакиваете из теней.",
["You pout at everyone around you."]="Вы дуетесь на всех окружающих.",
["You praise the Light."]="Вы возносите хвалу Свету.",
["You pray to the Gods."]="Вы молитесь богам.",
["You pull out your map."]="Вы достаете карту.",
["You punch yourself."]="Вы ударяете себя.",
["You purr like a kitten."]="Вы мурлычете, как котенок.",
["You put on the charm."]="Вы призываете на помощь весь свой шарм.",
["You put out a challenge to everyone. Bring it on!"]="Вы бросаете вызов всем вокруг. Давайте!",
["You put up your hand for a high five."]="Вы поднимаете руку для дружеского приветствия.",
["You quietly snicker to yourself."]="Вы молча давитесь от смеха.",
["You raise a drink in the air before chugging it down.  Cheers!"]="Вы поднимаете кубок. Будем здоровы!",
["You raise your eyebrow inquisitively."]="Вы вопросительно поднимаете бровь.",
["You raise your fist in anger."]="Вы в гневе заносите кулак.",
["You raise your hand in the air."]="Вы поднимаете руку.",
["You reached a new level. DING!"]="Вы достигли нового уровня. ДЗИНЬ!",
["You remain calm."]="Вы сохраняете спокойствие.",
["You roar with bestial vigor.  So fierce!"]="Вы бешено рычите. Какая ярость!",
["You roll on the floor laughing."]="Вы катаетесь по полу от смеха.",
["You roll your eyes."]="Вы закатываете глаза.",
["You ruffle your hair."]="Вы взъерошиваете себе волосы.",
["You run around in a frenzied state of panic."]="Вы в панике бегаете кругами.",
["You scoff."]="Вы усмехаетесь.",
["You scold yourself."]="Вы браните себя.",
["You scowl."]="Вы хмуритесь.",
["You scratch yourself.  Ah, much better!"]="Вы чешетесь. Полегчало!",
["You search for something."]="Вы что-то ищете.",
["You shake your fist."]="Вы потрясаете кулаком.",
["You shake your rear."]="Вы вертите задом.",
["You shimmy before the masses."]="Вы танцуете перед толпой.",
["You shiver in your boots. Chilling!"]="Вы зябко дрожите. Холодно!",
["You shoo the measly pests away."]="Вы отгоняете мерзких тварей.",
["You shout."]="Вы кричите.",
["You shrug.  Who knows?"]="Вы пожимаете плечами. Кто знает?",
["You shudder."]="Вас бросает в дрожь.",
["You slap yourself across the face. Ouch!"]="Вы бьете себя по лицу! Ох!",
["You smack your forehead."]="Вы хлопаете себя по лбу.",
["You smell the air around you. Wow, someone stinks!"]="Вы нюхаете воздух. Кем это воняет?",
["You smile shyly."]="Вы застенчиво улыбаетесь.",
["You smile."]="Вы улыбаетесь.",
["You snap your fingers."]="Вы щелкаете пальцами.",
["You sneeze. Achoo!"]="Вы чихаете. Апчхи!",
["You sniff the air around you."]="Вы нюхаете воздух.",
["You snort."]="Вы фыркаете.",
["You snub all of the lowly peons around you."]="Вы пренебрежительно выговариваете окружающим вас плебеям.",
["You spit on the ground."]="Вы плюете на землю.",
["You squeal like a pig."]="Вы визжите как свинья.",
["You stand at attention and salute."]="Вы становитесь навытяжку и отдаете честь.",
["You stare blankly at your surroundings."]="Вы бессмысленно таращитесь по сторонам.",
["You stare off into the distance."]="Вы пристально смотрите вдаль.",
["You start to charge."]="Вы идете в атаку.",
["You stretch your arms out."]="Вы потягиваетесь, разминая плечи.",
["You surrender to your opponents."]="Вы сдаетесь на милость победителей.",
["You take a deep breath."]="Вы глубоко вздыхаете.",
["You take a mighty quaff of your beverage."]="Вы одним глотком осушаете свою кружку.",
["You talk excitedly with everyone."]="Вы возбужденно говорите со всеми вокруг.",
["You talk to yourself since no one else seems interested."]="Вы разговариваете сами с собой, поскольку остальные вас не слушают.",
["You tap your foot.  Hurry up already!"]="Вы притопываете ногой. Ну, быстрее же!",
["You taunt everyone around you. Bring it fools!"]="Вы глумливо поддразниваете всех. Давайте, дураки!",
["You tell a joke."]="Вы рассказываете анекдот.",
["You tell everyone to attack something."]="Вы приказываете всем идти в атаку.",
["You tell everyone to be quiet. Shhh!"]="Вы велите всем замолчать. Тссс!",
["You tell everyone to go."]="Вы велите всем идти.",
["You tell everyone to stop attacking."]="Вы велите всем прекратить атаку.",
["You thank everyone around you."]="Вы благодарите всех.",
["You think everyone around you is a son of a motherless ogre."]="Вы думаете, что все вокруг отродья пьяного огра.",
["You think this is serious business."]="Вы думаете, что это нешуточное дело.",
["You threaten everyone with the wrath of doom."]="Вы пророчите всем кару небесную.",
["You try to pick up the pace."]="Вы пытаетесь не отставать.",
["You try to sneak away."]="Вы пытаетесь скрыться.",
["You twiddle your thumbs."]="Вы делаете одобрительный жест.",
["You veto the motion on the floor."]="Вы запрещаете всем двигаться.",
["You vow you will have your revenge."]="Вы даете клятву отомстить.",
["You want to be tickled.  Hee hee!"]="Вы хотите, чтобы вас пощекотали. Хи-хи!",
["You want to know the meaning of life."]="Вы хотите познать смысл жизни.",
["You want to make an offer."]="Вы хотите внести предложение.",
["You warn everyone of incoming enemies!"]="Вы кричите, что враги идут!",
["You warn everyone that an enemy is near."]="Вы предупреждаете всех, что враг близко.",
["You warn everyone."]="Вы предостерегаете всех.",
["You wave goodbye to everyone.  Farewell!"]="Вы машете всем рукой. До свидания!",
["You wave."]="Вы машете рукой.",
["You welcome everyone."]="Вы здороваетесь со всеми.",
["You were happy to help."]="Вы были рады помочь.",
["You were just kidding!"]="Вы просто пошутили!",
["You whine pathetically."]="Вы жалобно скулите.",
["You wink slyly."]="Вы хитро подмигиваете.",
["You wish everyone good luck."]="Вы желаете окружающим удачи.",
["You wish for some good luck."]="Вы желаете хоть немного удачи.",
["You wish someone would hold your hand."]="Вам хочется с кем-нибудь подержаться за руку.",
["You yawn sleepily."]="Вы сонно зеваете.",
["You yell for everyone to flee!"]="Вы кричите, чтобы все убегали!",
["You're too sexy for your tunic...so sexy it hurts."]="Вы чересчур сексуальны... прямо невыносимо!",
["Your eyes shift back and forth suspiciously."]="Вы подозрительно озираетесь по сторонам.",
}
CoARU_EMOTE_BY_WORD = {
["'s"]={
{"%s's eyes shift back and forth suspiciously.","%s подозрительно осматривается по сторонам."},
},
["a"]={
{"A tendril of drool runs down %s's lip.","Струйка слюны сползает с губ %s."},
{"A sly smirk spreads across %s's face.","На лице %s появляется хитрая усмешка."},
},
["agrees"]={
{"%s agrees with you.","%s соглашается с вами."},
{"%s agrees.","%s согласно кивает."},
{"%s agrees with %s.","%s соглашается с %s."},
},
["apologizes"]={
{"%s apologizes to everyone.  Sorry!","%s просит у всех прощения. Простите!"},
{"%s apologizes to you.  Sorry!","%s извиняется перед вами. Простите!"},
{"%s apologizes to %s.  Sorry!","%s извиняется перед %s."},
},
["applauds"]={
{"%s applauds at you.  Bravo!","%s рукоплещет вам. Браво!"},
{"%s applauds.  Bravo!","%s хлопает в ладоши. Браво!"},
{"%s applauds at %s.  Bravo!","%s рукоплещет %s. Браво!"},
},
["asks"]={
{"%s asks you to wait.","%s просит вас подождать."},
{"%s asks %s to wait.","%s просит %s подождать."},
},
["attempts"]={
{"%s attempts to make you an offer you can't refuse.","%s делает вам предложение, от которого невозможно отказаться."},
{"%s attempts to make %s an offer they can't refuse.","%s делает %s предложение, от которого невозможно отказаться."},
},
["bares"]={
{"%s bares his teeth and snarls at you.","%s скалится и ворчит на вас."},
{"%s bares her teeth and snarls at you.","%s скалится и рычит на вас."},
{"%s bares his teeth and snarls.","%s скалится и рычит."},
{"%s bares her teeth and snarls.","%s скалится и ворчит."},
{"%s bares his teeth and snarls at %s.","%s скалится и ворчит на %s."},
{"%s bares her teeth and snarls at %s.","%s скалится и рычит на %s."},
},
["barks"]={
{"%s barks. Woof woof!","%s лает. Гав-гав!"},
{"%s barks at you.","%s рявкает на вас."},
{"%s barks at %s.","%s рявкает на %s."},
},
["basks"]={
{"%s basks in the glory of victory with you.","%s вместе с вами упивается победой."},
{"%s basks in the glory of victory.","%s упивается победой."},
{"%s basks in the glory of victory with %s.","%s упивается славой вместе с %s."},
},
["beckons"]={
{"%s beckons everyone over.","%s жестом подзывает всех."},
{"%s beckons you over.","%s жестом подзывает вас."},
{"%s beckons %s over.","%s жестом подзывает %s."},
},
["begins"]={
{"%s begins to play the world's smallest violin.","%s начинает играть на маленькой скрипочке."},
{"%s begins to eat rations in front of you.","%s начинает подъедать припасы у вас на глазах."},
{"%s begins to groan.","%s начинает стонать."},
{"%s begins to work.","%s начинает работать."},
{"%s begins to eat.","%s начинает есть."},
{"%s begins to eat in front of %s.","%s начинает есть на глазах у %s."},
},
["begs"]={
{"%s begs everyone around him.  How pathetic.","%s умоляет всех. Жалкое зрелище!"},
{"%s begs everyone around her.  How pathetic.","%s с мольбой смотрит на окружающих. Выглядит жалко."},
{"%s begs you.  How pathetic.","%s с мольбой смотрит на вас. Выглядит жалко."},
{"%s begs %s.  How pathetic.","%s умоляет %s. Ничтожество!"},
},
["bites"]={
{"%s bites you.  Ouch!","%s кусает вас. Ой!"},
{"%s bites %s.  Ouch!","%s кусает %s. Ой!"},
},
["blames"]={
{"%s blames himself for what happened.","%s обвиняет всех, кроме себя."},
{"%s blames herself for what happened.","%s обвиняет всех, кроме себя."},
{"%s blames you for everything.","%s обвиняет вас во всем."},
{"%s blames %s for everything.","%s винит во всем %s."},
},
["blinks"]={
{"%s blinks at you.","%s моргает, глядя на вас."},
{"%s blinks.","%s моргает."},
{"%s blinks at %s.","%s моргает, глядя на %s."},
},
["blood"]={
{"Blood oozes from %s's wounds.","Раны %s кровоточат."},
},
["blows"]={
{"%s blows a kiss into the wind.","%s посылает воздушный поцелуй."},
{"%s blows you a kiss.","%s посылает вам воздушный поцелуй."},
{"%s blows %s a kiss.","%s посылает воздушный поцелуй %s."},
},
["blushes"]={
{"%s blushes at you.","%s вспыхивает при виде вас."},
{"%s blushes.","%s заливается краской."},
{"%s blushes at %s.","%s заливается краской при виде %s."},
},
["boggles"]={
{"%s boggles at the situation.","%s разводит руками в замешательстве."},
{"%s boggles at you.","%s изумленно смотрит на вас."},
{"%s boggles at %s.","%s изумленно смотрит на %s."},
},
["bonks"]={
{"%s bonks you on the noggin.  Doh!","%s бьет вас по голове. Буммм!"},
{"%s bonks his own noggin.  Doh!","%s бьет себя по голове. Буммм!"},
{"%s bonks her own noggin.  Doh!","%s бьет себя по голове. Буммм!"},
{"%s bonks %s on the noggin.  Doh!","%s бьет %s по голове. Буммм!"},
},
["bounces"]={
{"%s bounces up and down in front of you.","%s прыгает на месте перед вами."},
{"%s bounces up and down.","%s прыгает на месте."},
{"%s bounces up and down in front of %s.","%s прыгает на месте перед %s."},
},
["bows"]={
{"%s bows down graciously.","%s изящно кланяется."},
{"%s bows before you.","%s кланяется вам."},
{"%s bows before %s.","%s кланяется %s."},
},
["brandishes"]={
{"%s brandishes his weapon fiercely at you.","%s яростно замахивается своим оружием на вас."},
{"%s brandishes her weapon fiercely at you.","%s в ярости замахивается на вас."},
{"%s brandishes his weapon fiercely.","%s яростно размахивает оружием."},
{"%s brandishes her weapon fiercely.","%s яростно размахивает своим оружием."},
{"%s brandishes his weapon fiercely at %s.","%s яростно замахивается своим оружием на %s."},
{"%s brandishes her weapon fiercely at %s.","%s яростно замахивается оружием на %s."},
},
["brushes"]={
{"%s brushes up against you and farts loudly.","%s трется о вас и громко испускает газы."},
{"%s brushes up against %s and farts loudly.","%s трется о %s и громко испускает газы."},
},
["burps"]={
{"%s burps rudely in your face.","%s грубо рыгает вам в лицо."},
{"%s burps rudely in %s's face.","%s грубо рыгает в лицо %s."},
},
["bursts"]={
{"%s bursts into dance.","%s пускается в пляс."},
{"%s bursts into song.","%s запевает."},
},
["cackles"]={
{"%s cackles maniacally at the situation.","%s громко хохочет."},
{"%s cackles maniacally at you.","%s громко хохочет над вами."},
{"%s cackles maniacally at %s.","%s громко хохочет над %s."},
},
["calls"]={
{"%s calls out for healing!","%s зовет лекаря!"},
},
["challenges"]={
{"%s challenges you to a duel.","%s вызывает вас на дуэль."},
{"%s challenges %s to a duel.","%s вызывает %s на дуэль."},
},
["checks"]={
{"%s checks you for a pulse.","%s проверяет, есть ли у вас пульс."},
{"%s checks his own pulse.","%s проверяет свой пульс."},
{"%s checks her own pulse.","%s проверяет свой пульс."},
{"%s checks %s for a pulse. Oh no!","%s проверяет, есть ли у %s пульс. О нет!"},
},
["cheers"]={
{"%s cheers at you.","%s радуется вашим успехам."},
{"%s cheers!","%s не может сдержать радости!"},
{"%s cheers at %s!","%s радуется успехам %s!"},
},
["chuckles"]={
{"%s chuckles at you.","%s хихикает над вами."},
{"%s chuckles at %s.","%s хихикает при виде %s."},
},
["claps"]={
{"%s claps half-heartedly, clearly unimpressed.","%s вяло аплодирует."},
{"%s claps for you, clearly unimpressed.","%s равнодушно аплодирует вам."},
{"%s claps excitedly for you.","%s воодушевленно аплодирует вам."},
{"%s claps excitedly.","%s восторженно рукоплещет."},
{"%s claps for %s, clearly unimpressed.","%s подчеркнуто равнодушно аплодирует %s."},
{"%s claps excitedly for %s.","%s восторженно рукоплещет %s."},
},
["clearly"]={
{"%s clearly states, NO.","%s твердо заявляет: \"НЕТ!\""},
},
["comforts"]={
{"%s comforts you.","%s утешает вас."},
{"%s comforts %s.","%s утешает %s."},
},
["commends"]={
{"%s commends everyone on a job well done.","%s хвалит всех за хорошую работу."},
{"%s commends you on a job well done.","%s благодарит вас за хорошую работу."},
{"%s commends %s on a job well done.","%s хвалит %s за хорошую работу."},
},
["congratulates"]={
{"%s congratulates you on a new level. DING!","%s поздравляет вас с новым уровнем. ДЗИНЬ!"},
{"%s congratulates everyone.","%s поздравляет всех."},
{"%s congratulates you.","%s поздравляет вас."},
{"%s congratulates %s on a new level. DING!","%s поздравляет 3-3(%s) с новым уровнем. ДЗИНЬ!"},
{"%s congratulates %s.","%s поздравляет %s."},
},
["coughs"]={
{"%s coughs at you.","%s кашляет, пытаясь привлечь ваше внимание."},
{"%s coughs at %s.","%s кашляет, пытаясь привлечь внимание %s."},
},
["covers"]={
{"%s covers his face with his palm.","%s прячет лицо в ладонях."},
{"%s covers her face with her palm.","%s прячет лицо в ладонях."},
{"%s covers your ears.","%s закрывает вам уши."},
{"%s covers his ears.","%s закрывает уши."},
{"%s covers her ears.","%s закрывает уши."},
{"%s covers %s's ears.","%s закрывает %s уши."},
},
["cowers"]={
{"%s cowers in fear at the sight of you.","%s дрожит от страха при виде вас."},
{"%s cowers in fear.","%s съеживается от страха."},
{"%s cowers in fear at the sight of %s.","%s дрожит от страха при виде %s."},
},
["cracks"]={
{"%s cracks his knuckles while staring at you.","%s похрустывает костяшками пальцев, глядя на вас."},
{"%s cracks her knuckles while staring at you.","%s похрустывает костяшками пальцев, глядя на вас."},
{"%s cracks his knuckles.","%s похрустывает костяшками пальцев."},
{"%s cracks her knuckles.","%s похрустывает костяшками пальцев."},
{"%s cracks his knuckles while staring at %s.","%s похрустывает костяшками пальцев, глядя на %s."},
{"%s cracks her knuckles while staring at %s.","%s похрустывает костяшками пальцев, глядя на %s."},
},
["cries"]={
{"%s cries on your shoulder.","%s рыдает у вас на плече."},
{"%s cries out for help!","%s зовет на помощь!"},
{"%s cries.","%s плачет."},
{"%s cries on %s's shoulder.","%s рыдает на плече %s."},
},
["cringes"]={
{"%s cringes away from you.","%s съеживается и пятится от вас."},
{"%s cringes in fear.","%s сжимается от страха."},
{"%s cringes away from %s.","%s пятится от %s."},
},
["crosses"]={
{"%s crosses his arms at you. Hmph!","%s скрещивает руки, глядя на вас. Хм!"},
{"%s crosses her arms at you. Hmph!","%s скрещивает руки, глядя на вас. Хм!"},
{"%s crosses his arms.","%s скрещивает руки."},
{"%s crosses her arms.","%s скрещивает руки."},
{"%s crosses his arms at %s. Hmph!","%s скрещивает руки, глядя на %s. Хм!"},
{"%s crosses her arms at %s. Hmph!","%s скрещивает руки, глядя на %s. Хм!"},
},
["cuddles"]={
{"%s cuddles up against you.","%s прижимается к вам."},
{"%s cuddles up against %s.","%s прижимается к %s."},
},
["curtsies"]={
{"%s curtsies before you.","%s делает перед вами реверанс."},
{"%s curtsies.","%s делает реверанс."},
{"%s curtsies before %s.","%s приседает перед %s."},
},
["dances"]={
{"%s dances with you.","%s танцует с вами."},
{"%s dances with %s.","%s танцует с %s."},
},
["digs"]={
{"%s digs through his backpack.","%s роется в своем рюкзаке."},
{"%s digs through her backpack","%s роется в своем рюкзаке."},
},
["disagrees"]={
{"%s disagrees with you.","%s не соглашается с вами."},
{"%s disagrees.","%s не соглашается."},
{"%s disagrees with %s.","%s не соглашается с %s."},
},
["doubts"]={
{"%s doubts the situation will end in his favor.","%s сомневается, что ситуация разрешится в его пользу."},
{"%s doubts the situation will end in her favor.","%s сомневается, что ситуация разрешится в ее пользу."},
{"%s doubts you.","%s сомневается в вас."},
{"%s doubts %s.","%s сомневается в %s."},
},
["drops"]={
{"%s drops to his knees and pleads in desperation.","%s падает на колени в отчаянной мольбе."},
{"%s drops to her knees and plead in desperation.","%s падает на колени в отчаянной мольбе."},
{"%s drops his trousers and moons everyone.","%s снимает штаны и показывает всем зад."},
{"%s drops her trousers and moons everyone.","%s снимает штаны и показывает всем зад."},
{"%s drops his trousers and moons you.","%s снимает штаны и показывает вам зад."},
{"%s drops her trousers and moons you.","%s снимает штаны и показывает вам зад."},
{"%s drops his trousers and moons %s.","%s снимает штаны и показывает зад %s."},
{"%s drops her trousers and moons %s.","%s показывает голый зад %s."},
},
["ducks"]={
{"%s ducks behind you.","%s прячется за вашу спину."},
{"%s ducks for cover.","%s ищет укрытие."},
{"%s ducks behind %s.","%s прячется за спину %s."},
},
["encourages"]={
{"%s encourages everyone around him. You can do it!","%s подбадривает всех вокруг. Вы справитесь!"},
{"%s encourages everyone around her. You can do it!","%s подбадривает всех вокруг. Вы справитесь!"},
{"%s encourages you to chug. CHUG! CHUG! CHUG!","%s подначивает вас изобразить выпить до дна. ПЕЙ ДО ДНА!"},
{"%s encourages you. You can do it!","%s подбадривает вас. Вы можете это сделать!"},
{"%s encourages %s to chug. CHUG! CHUG! CHUG!","%s подначивает %s пить до дна. ПЕЙ ДО ДНА!"},
{"%s encourages %s.","%s подбадривает %s."},
},
["expresses"]={
{"%s expresses his curiosity to everyone.","%s демонстрирует всем свое любопытство."},
{"%s expresses her curiosity to everyone.","%s показывает окружающим свое любопытство."},
},
["eyes"]={
{"%s eyes you up and down.","%s меряет вас взглядом."},
{"%s eyes %s up and down.","%s меряет взглядом %s."},
},
["faints"]={
{"%s faints at the sight of you.","%s падает в обморок при виде вас."},
{"%s faints.","%s падает в обморок."},
{"%s faints at the sight of %s.","%s падает в обморок при виде %s."},
},
["falls"]={
{"%s falls asleep. Zzzzzzz.","%s засыпает. Хррррррр."},
},
["farts"]={
{"%s farts loudly.  Whew...what stinks?","%s шумно испускает газы. Фу… что за вонь?"},
},
["feels"]={
{"%s feels the love.","%s ощущает любовь ближних."},
},
["fidgets"]={
{"%s fidgets impatiently while waiting for you.","%s нервничает, с нетерпением ожидая вас."},
{"%s fidgets.","%s нервничает."},
{"%s fidgets impatiently while waiting for %s.","%s нервничает, ожидая %s."},
},
["flexes"]={
{"%s flexes his muscles.  Oooooh so strong!","%s поигрывает мускулами. Какая сила!"},
{"%s flexes her muscles.  Oooooh so strong!","%s поигрывает мускулами. Какая сила!"},
{"%s flexes at you.  Oooooh so strong!","%s поигрывает мускулами. Какая сила!"},
{"%s flexes at %s.  Oooooh so strong!","%s поигрывает мускулами перед %s. Какая сила!"},
},
["flirts"]={
{"%s flirts with you.","%s флиртует с вами."},
{"%s flirts.","%s флиртует."},
{"%s flirts with %s.","%s флиртует с %s."},
},
["flops"]={
{"%s flops about helplessly around you.","%s беспомощно суетится вокруг вас."},
{"%s flops about helplessly.","%s беспомощно суетится."},
{"%s flops about helplessly around %s.","%s беспомощно суетится вокруг %s."},
},
["flushes"]={
{"%s flushes with embarrassment.","%s вспыхивает от смущения."},
},
["frowns"]={
{"%s frowns with disappointment at you.","%s хмуро глядит на вас."},
{"%s frowns.","%s хмурится."},
{"%s frowns with disappointment at %s.","%s досадливо хмурится, глядя на %s."},
},
["gasps"]={
{"%s gasps at you.","%s ахает при виде вас."},
{"%s gasps.","%s ахает."},
{"%s gasps at %s.","%s ахает при виде %s."},
},
["gazes"]={
{"%s gazes off into the distance.","%s смотрит куда-то вдаль."},
{"%s gazes longingly at you.","%s пожирает вас вас взглядом."},
{"%s gazes longingly at %s.","%s пожирает взглядом %s."},
},
["gently"]={
{"%s gently pats you.","%s ласково гладит вас."},
{"%s gently pats %s.","%s ласково гладит %s."},
},
["giggles"]={
{"%s giggles at you.","%s хихикает при виде вас."},
{"%s giggles.","%s хихикает."},
{"%s giggles at %s.","%s хихикает, глядя на %s."},
},
["gives"]={
{"%s gives you a shifty look.","%s хитро поглядывает на вас."},
{"%s gives you a high five!","%s по-дружески здоровается с вами!"},
{"%s gives you the signal.","%s подает вам сигнал."},
{"%s gives the signal.","%s подает сигнал."},
{"%s gives %s a shifty look.","%s хитро поглядывает на %s."},
{"%s gives %s a high five!","%s по-дружески здоровается с %s!"},
{"%s gives %s the signal.","%s подает %s сигнал."},
},
["glares"]={
{"%s glares angrily at you.","%s бросает на вас гневный взгляд."},
{"%s glares angrily.","%s смотрит исподлобья."},
{"%s glares angrily at %s.","%s бросает гневный взгляд на %s."},
},
["gloats"]={
{"%s gloats over everyone's misfortune.","%s злорадствует по поводу общей неудачи."},
{"%s gloats over your misfortune.","%s злорадствует по поводу вашей неудачи."},
{"%s gloats over %s's misfortune.","%s злорадствует по поводу неудачи %s."},
},
["glowers"]={
{"%s glowers at everyone around him.","%s зло смотрит на всех окружающих."},
{"%s glowers at everyone around her.","%s зло смотрит на всех окружающих."},
{"%s glowers at you.","%s зло смотрит на вас."},
{"%s glowers at %s.","%s зло смотрит на %s"},
},
["greets"]={
{"%s greets everyone with a hearty hello!","%s сердечно приветствует всех вокруг!"},
{"%s greets you with a hearty hello!","%s сердечно приветствует вас!"},
{"%s greets everyone warmly.","%s всех тепло приветствует."},
{"%s greets you warmly.","%s тепло вас приветствует."},
{"%s greets %s with a hearty hello!","%s сердечно приветствует %s!"},
{"%s greets %s warmly.","%s тепло приветствует %s."},
},
["grins"]={
{"%s grins at you wickedly.","%s злобно скалится на вас."},
{"%s grins wickedly.","%s злобно ухмыляется."},
{"%s grins wickedly at %s.","%s злобно ухмыляется %s."},
},
["grovels"]={
{"%s grovels on the ground, wallowing in subservience.","%s ползает на брюхе, выражая покорность."},
{"%s grovels before you like a subservient peon.","%s ползает перед вами, как услужливый слуга."},
{"%s grovels before %s like a subservient peon.","%s ползает на брюхе перед %s, как услужливый слуга."},
},
["growls"]={
{"%s growls menacingly at you.","%s угрожающе рычит на вас."},
{"%s growls menacingly.","%s угрожающе рычит."},
{"%s growls menacingly at %s.","%s угрожающе рычит на %s."},
},
["hails"]={
{"%s hails everyone around him.","%s приветствует всех вокруг."},
{"%s hails everyone around her.","%s приветствует всех вокруг."},
{"%s hails you.","%s приветствует вас."},
{"%s hails %s.","%s приветствует %s."},
},
["hangs"]={
{"%s hangs his head dejectedly.","%s уныло вешает голову."},
{"%s hangs her head dejectedly.","%s уныло вешает голову."},
},
["has"]={
{"%s has a bad feeling about this...","%s кажется, что ничем хорошим это не закончится..."},
{"%s has a bad feeling about you.","У %s плохие предчувствия на ваш счет."},
{"%s has an idea!","У %s есть идея!"},
{"%s has failed.","%s постигла неудача."},
{"%s has a bad feeling about %s.","У %s предчувствие, что сейчас %s все испортит."},
},
["hiccups"]={
{"%s hiccups loudly.","%s громко икает."},
},
["hisses"]={
{"%s hisses at everyone around him.","%s шипит на окружающих."},
{"%s hisses at everyone around her.","%s шипит на окружающих."},
{"%s hisses at you.","%s шипит на вас."},
{"%s hisses at %s.","%s шипит на %s."},
},
["holds"]={
{"%s holds your hand.","%s здоровается с вами за руку."},
{"%s holds %s's hand.","%s здоровается с %s за руку."},
},
["hugs"]={
{"%s hugs you.","%s крепко обнимает вас."},
{"%s hugs %s.","%s крепко обнимает %s."},
},
["in"]={
{"In quiet contemplation, %s mourns the loss of the dead.","В глубоком молчании %s скорбит по погибшим."},
{"In quiet contemplation, you mourn the death of %s.","В глубоком молчании вы скорбите о гибели %s."},
{"In quiet contemplation, %s mourns your death.","В глубоком молчании %s скорбит о вашей смерти."},
{"In quiet contemplation, %s mourns the death of %s.","В глубоком молчании %s скорбит о смерти %s."},
},
["introduces"]={
{"%s introduces himself to everyone.","%s представляется всем."},
{"%s introduces herself to everyone.","%s представляется всем."},
{"%s introduces himself to you.","%s представляется вам."},
{"%s introduces herself to you.","%s представляется вам."},
{"%s introduces himself to %s.","%s представляется %s."},
{"%s introduces herself to %s.","%s представляется %s."},
},
["is"]={
{"%s is so bashful...too bashful to get your attention.","%s стесняется привлечь ваше внимание."},
{"%s is too sexy for his tunic...so sexy it hurts.","%s слишком сексуален... Невыносимо!"},
{"%s is too sexy for her tunic...so sexy it hurts.","%s слишком сексуальна... прямо невыносимо!"},
{"%s is overcome with boredom.  Oh the drudgery!","%s изнывает от скуки. Какое занудство!"},
{"%s is so thirsty. Can anyone spare a drink?","%s очень хочет пить. Никто не даст глоточек?"},
{"%s is hungry.  Maybe you have some food...","%s хочет есть. Может, у вас найдется какая-нибудь еда..."},
{"%s is getting a headache from your antics.","У %s болит голова от ваших кривляний."},
{"%s is jealous of everyone around him.","%s завидует всем вокруг."},
{"%s is jealous of everyone around her.","%s завидует всем вокруг."},
{"%s is puzzled. What's going on here?","%s в недоумении. Что тут происходит?"},
{"%s is curious what you are up to.","%s интересуется, что вы собираетесь делать."},
{"%s is surprised by your actions.","%s удивляют ваши действия."},
{"%s is terribly bored with you.","Вы окончательно утомили %s."},
{"%s is filled with happiness!","%s переполняет счастье!"},
{"%s is hopelessly confused.","%s в полном недоумении."},
{"%s is very happy with you!","Вы очень угодили %s!"},
{"%s is embarrassed by you.","Вы смутили %s."},
{"%s is getting a headache.","У %s болит голова."},
{"%s is filled with regret.","%s переполняет сожаление."},
{"%s is suspicious of you.","Кажется, %s в чем-то вас подозревает."},
{"%s is proud of himself.","%s гордится собой."},
{"%s is proud of herself.","%s гордится собой."},
{"%s is hopelessly lost.","%s в полном недоумении."},
{"%s is lost in thought.","%s погрузился в раздумья."},
{"%s is jealous of you.","%s завидует вам."},
{"%s is amazed by you!","%s восхищается вами!"},
{"%s is scared of you.","%s пугается вас."},
{"%s is so surprised!","%s в таком удивлении!"},
{"%s is such a tease.","%s – такая язва!"},
{"%s is proud of you.","%s гордится вами."},
{"%s is low on mana.","%s предупреждает, что мана на исходе."},
{"%s is listening!","%s слушает!"},
{"%s is sweating.","%s покрывается потом."},
{"%s is bashful.","%s краснеет."},
{"%s is amazed!","%s в восхищении!"},
{"%s is hungry!","%s хочет есть!"},
{"%s is scared!","%s в испуге!"},
{"%s is so bashful...too bashful to get %s's attention.","%s стесняется привлечь внимание %s."},
{"%s is getting a headache from %s's antics.","У %s болит голова от кривляний %s."},
{"%s is hungry.  Maybe %s has some food...","%s хочет есть. Может, у %s найдется какая-нибудь еда..."},
{"%s is surprised by %s's actions.","%s в недоумении от действий %s."},
{"%s is curious what %s is up to.","%s интересно, что будет делать %s."},
{"%s is terribly bored with %s.","%2$s окончательно утомляет %1$s."},
{"%s is very happy with %s!","%s не может нарадоваться %s!"},
{"%s is embarrassed by %s.","%s в растерянности от действий %s."},
{"%s is suspicious of %s.","%s в чем-то подозревает %s."},
{"%s is puzzled by %s.","%s не понимает %s."},
{"%s is jealous of %s.","%s завидует %s."},
{"%s is amazed by %s!","%s восхищается %s!"},
{"%s is scared of %s.","%s пугается %s."},
{"%s is proud of %s.","%s гордится %s."},
},
["kneels"]={
{"%s kneels before you.","%s преклоняет колени перед вами."},
{"%s kneels down.","%s преклоняет колени."},
{"%s kneels before %s.","%s преклоняет колени перед %s."},
},
["laughs"]={
{"%s laughs at you.","%s смеется над вами."},
{"%s laughs.","%s смеется."},
{"%s laughs at %s.","%s смеется над %s."},
},
["lavishes"]={
{"%s lavishes praise upon you.","%s восхваляет вас."},
{"%s lavishes praise upon %s.","%s превозносит %s."},
},
["lets"]={
{"%s lets you know she is thirsty. Spare a drink?","%s показывает вам, что хочет пить. Дадите глоточек?"},
{"%s lets you know he is thirsty. Spare a drink?","%s показывает вам, что хочет пить. Дадите глоточек?"},
{"%s lets you know that she was just kidding!","%s показывает, что просто пошутила!"},
{"%s lets you know that he was just kidding!","%s показывает вам, что он всего лишь пошутил!"},
{"%s lets everyone know that she is tired.","%s показывает всем, что она устала."},
{"%s lets everyone know that she is ready!","%s показывает всем, что готова!"},
{"%s lets everyone know that he is tired.","%s показывает всем, что он устал."},
{"%s lets everyone know that she is cold.","%s показывает всем, что ей холодно."},
{"%s lets everyone know that he is ready!","%s показывает всем, что он готов!"},
{"%s lets everyone know that he is cold.","%s показывает всем, что ему холодно."},
{"%s lets out a long, drawn-out sigh.","%s испускает долгий, усталый вздох."},
{"%s lets you know that she is tired.","%s показывает вам, что она устала."},
{"%s lets you know that she is ready!","%s показывает вам, что готова!"},
{"%s lets you know that he is tired.","%s показывает вам, что устал."},
{"%s lets you know that she is cold.","%s показывает вам, что ей холодно."},
{"%s lets you know that he is ready!","%s показывает вам, что готов!"},
{"%s lets you know that he is cold.","%s показывает вам, что ему холодно."},
{"%s lets out a boisterous guffaw!","%s громко смеется!"},
{"%s lets forth a sharp whistle.","%s пронзительно свистит."},
{"%s lets out a hearty chuckle.","%s от души хихикает."},
{"%s lets out a hacking cough.","%s отрывисто кашляет."},
{"%s lets out a loud belch.","%s громко рыгает."},
{"%s lets %s know she is thirsty. Spare a drink?","%s показывает %s, что хочет пить. Не дадите глоточек?"},
{"%s lets %s know he is thirsty. Spare a drink?","%s показывает %s, что хочет пить. Дадите глоточек?"},
{"%s lets %s know that she was just kidding!","%s дает понять %s, что это была всего лишь шутка!"},
{"%s lets %s know that he was just kidding!","%s показывает %s, что это была всего лишь шутка!"},
{"%s lets %s know that she is tired.","%s показывает %s, что она устала."},
{"%s lets %s know that she is ready!","%s показывает %s, что она готова!"},
{"%s lets %s know that he is tired.","%s показывает %s, что он устал."},
{"%s lets %s know that she is cold.","%s показывает %s, что ей холодно."},
{"%s lets %s know that he is ready!","%s показывает %s, что готов!"},
{"%s lets %s know that he is cold.","%s показывает %s, что ему холодно."},
},
["licks"]={
{"%s licks his lips.","%s облизывается."},
{"%s licks her lips.","%s облизывается."},
{"%s licks you.","%s облизывает вас."},
{"%s licks %s.","%s облизывает %s."},
},
["lies"]={
{"%s lies down before you.","%s ложится перед вами."},
{"%s lies down.","%s ложится."},
{"%s lies down before %s.","%s ложится перед %s."},
},
["listens"]={
{"%s listens intently to you.","%s внимательно слушает вас."},
{"%s listens intently to %s.","%s внимательно слушает %s."},
},
["looks"]={
{"%s looks at you and covers his face with his palm.","%s смотрит на вас и прячет лицо в ладонях."},
{"%s looks at you and covers her face with her palm.","%s смотрит на вас и прячет лицо в ладонях."},
{"%s looks at you with a confused look.","%s с недоумением смотрит на вас."},
{"%s looks around for someone to bite.","%s ищет, кого бы покусать."},
{"%s looks at you and begins to drool.","%s млеет, глядя на вас."},
{"%s looks at you and raises his hand.","%s смотрит на вас и поднимает руку."},
{"%s looks at you and raises her hand.","%s смотрит на вас и поднимает руку."},
{"%s looks at you with crossed eyes.","%s окосевши смотрит на вас."},
{"%s looks down upon you with pity.","%s меряет вас полным жалости взглядом."},
{"%s looks at you and groans.","%s смотрит на вас и стонет."},
{"%s looks at you nervously.","%s обеспокоено смотрит на вас."},
{"%s looks around nervously.","%s нервно оглядывается."},
{"%s looks at you absently.","%s смотрит на вас отсутствующим взглядом."},
{"%s looks absent-minded.","Кажется, %s сбит с толку."},
{"%s looks around in awe.","%s оглядывается вокруг с благоговейным трепетом."},
{"%s looks at you.","%s смотрит на вас."},
{"%s looks around.","%s оглядывается."},
{"%s looks at %s and covers his face with his palm.","%s смотрит на %s и прячет лицо в ладонях."},
{"%s looks at %s and covers her face with her palm.","%s смотрит на %s и прячет лицо в ладонях."},
{"%s looks at %s and raises his hand in the air.","%s смотрит на %s и поднимает руку."},
{"%s looks at %s and raises her hand in the air.","%s смотрит на %s и поднимает руку."},
{"%s looks at %s with a confused look.","%s недоуменно смотрит на %s."},
{"%s looks at %s and begins to drool.","%s млеет, глядя на %s."},
{"%s looks down upon %s with pity.","%s с жалостью взирает на %s."},
{"%s looks at %s and groans.","%s смотрит на %s и стонет."},
{"%s looks at %s nervously.","%s обеспокоенно смотрит на %s"},
{"%s looks at %s absently.","%s смотрит на %s отсутствующим взглядом."},
{"%s looks at %s.","%s смотрит на %s."},
},
["loves"]={
{"%s loves you.","%s любит вас."},
{"%s loves %s.","%s любит %s."},
},
["makes"]={
{"%s makes a taunting gesture at you. Bring it!","%s глумливо поддразнивает вас. Ну, давай!"},
{"%s makes a rude gesture at you.","%s делает в вашу сторону неприличный жест."},
{"%s makes a rude gesture.","%s делает неприличный жест."},
{"%s makes you a promise.","%s дает вам обещание."},
{"%s makes a taunting gesture at %s. Bring it!","%s глумливо дразнит %s. Ну, давай!"},
{"%s makes a rude gesture at %s.","%s делает неприличный жест в сторону %s."},
{"%s makes %s a promise.","%s даете %s обещание."},
},
["massages"]={
{"%s massages your shoulders.","%s растирает вам плечи."},
{"%s massages %s's shoulders.","%s массирует плечи %s."},
},
["moans"]={
{"%s moans suggestively at you.","%s призывно стонет перед вами."},
{"%s moans suggestively.","%s призывно стонет."},
{"%s moans suggestively at %s.","%s призывно стонет перед %s."},
},
["mocks"]={
{"%s mocks life and all it stands for.","%s высмеивает жизнь и все, что с ней связано."},
{"%s mocks your foolishness.","%s смеется над вашей глупостью."},
{"%s mocks the foolishness of %s.","%s смеется над глупостью %s."},
},
["moos"]={
{"%s moos at you. Mooooooooooo.","%s мычит на вас. Муууууууу!"},
{"%s moos. Mooooooooooo.","%s мычит. Муууууууу!"},
{"%s moos at %s. Mooooooooooo.","%s мычит на %s. Муууууууу!"},
},
["motions"]={
{"%s motions for you to follow.","%s жестом велит вам следовать за собой."},
{"%s motions for %s to follow.","%s жестом велит %s следовать за собой."},
},
["must"]={
{"%s must be going.","%s пора уходить."},
},
["mutters"]={
{"%s mutters angrily to himself. Hmmmph!","%s зло бормочет себе под нос. Гхмммм!"},
{"%s mutters angrily to herself. Hmmmph!","%s зло бормочет себе под нос. Гхмммм!"},
{"%s mutters angrily at you. Hmmmph!","%s зло бормочет, обращаясь к вам. Гхмммм!"},
{"%s mutters angrily at %s. Hmmmph!","%s зло бормочет, обращаясь к %s. Гхмммм!"},
},
["narrows"]={
{"%s narrows his eyes in suspicion.","%s недоверчиво щурится."},
{"%s narrows her eyes in suspicion.","%s недоверчиво щурится."},
},
["needs"]={
{"%s needs to be soothed.","%s нуждается в утешении."},
{"%s needs to be petted.","%s требует ласки."},
{"%s needs comforting.","%s нуждается в утешении."},
{"%s needs a massage!","%s нужен массаж!"},
{"%s needs cuddling.","%s хочет ласки."},
{"%s needs a hug!","%s хочет ласки!"},
{"%s needs a pat.","%s нужно погладить."},
},
["nods"]={
{"%s nods at you.","%s кивает вам."},
{"%s nods.","%s кивает."},
{"%s nods at %s.","%s кивает %s."},
},
["objects"]={
{"%s objects to you.","%s возражает вам."},
{"%s OBJECTS!","%s ПРОТЕСТУЕТ!"},
{"%s objects to %s.","%s возражает %s."},
},
["offers"]={
{"%s offers you a truce.","%s предлагает вам перемирие."},
{"%s offers a truce.","%s предлагает перемирие."},
{"%s offers %s a truce.","%s предлагает %s перемирие."},
},
["orders"]={
{"%s orders you to open fire.","%s приказывает вам открыть огонь."},
},
["passes"]={
{"%s passes the time with a finger deep in one nostril.","%s коротает время, копаясь в носу."},
},
["peers"]={
{"%s peers around, searchingly.","%s внимательно осматривается."},
{"%s peers at you searchingly.","%s испытующе смотрит на вас."},
{"%s peers at %s searchingly.","%s испытующе смотрит на %s."},
},
["pets"]={
{"%s pets you.","%s поглаживает вас."},
{"%s pets %s.","%s поглаживает %s."},
},
["picks"]={
{"%s picks his nose and shows it to you.","%s достает из носа козявку и показывает вам."},
{"%s picks her nose and shows it to you.","%s достает из носа козявку и показывает вам."},
{"%s picks his nose and shows it to %s.","%s выковыривает из носу козявку и показывает ее %s."},
{"%s picks her nose and shows it to %s.","%s выковыривает из носа козявку и показывает %s."},
},
["pinches"]={
{"%s pinches himself.","%s щипает себя."},
{"%s pinches herself.","%s щипает себя."},
{"%s pinches you.","%s щипает вас."},
{"%s pinches %s.","%s щипает %s."},
},
["pities"]={
{"%s pities those around him.","%s жалеет окружающих."},
{"%s pities those around her.","%s жалеет окружающих."},
},
["plays"]={
{"%s plays the world's smallest violin for you.","%s играет для вас на маленькой скрипочке."},
{"%s plays the world's smallest violin for %s.","%s играет для %s на маленькой скрипочке."},
},
["pleads"]={
{"%s pleads with you for mercy.","%s умоляет вас о пощаде."},
{"%s pleads for mercy.","%s просит о пощаде."},
{"%s pleads with you.","%s умоляет вас."},
{"%s pleads with %s for mercy.","%s просит %s о пощаде."},
{"%s pleads with %s.","%s умоляет %s."},
},
["points"]={
{"%s points you out as an incoming enemy!","%s указывает на вас как на врага!"},
{"%s points over yonder.","%s показывает в ту сторону."},
{"%s points at you.","%s показывает на вас."},
{"%s points out the incoming enemy, %s!","%s указывает на %s как на врага!"},
{"%s points at %s.","%s показывает на %s."},
},
["pokes"]={
{"%s pokes his belly and giggles.","%s тычет себя в живот и хихикает."},
{"%s pokes her belly and giggles.","%s тычет себя в живот и хихикает."},
{"%s pokes you.  Hey!","%s пихает вас локтем. Эй!"},
{"%s pokes %s.  Hey!","%s пихает %s локтем. Эй!"},
},
["ponders"]={
{"%s ponders the situation.","%s обдумывает ситуацию."},
{"%s ponders your actions.","%s обдумывает ваши действия."},
{"%s ponders %s's actions.","%s обдумывает действия %s."},
},
["pounces"]={
{"%s pounces out from the shadows.","%s внезапно выскакивает из теней."},
{"%s pounces on top of you.","%s бросается на вас."},
{"%s pounces on top of %s.","%s бросается на %s."},
},
["pouts"]={
{"%s pouts at everyone around him.","%s дуется на всех окружающих."},
{"%s pouts at everyone around her.","%s дуется на всех окружающих."},
{"%s pouts at you.","%s дуется на вас."},
{"%s pouts at %s.","%s дуется на %s."},
},
["praises"]={
{"%s praises the Light.","%s возносит хвалу Свету."},
},
["prays"]={
{"%s prays to the Gods.","%s молится богам."},
},
["pulls"]={
{"%s pulls out his map.","%s достает карту."},
{"%s pulls out her map.","%s достает карту."},
},
["punches"]={
{"%s punches your shoulder.","%s ударяет вас в плечо."},
{"%s punches himself.","%s бьет себя кулаком."},
{"%s punches herself.","%s бьет себя кулаком."},
{"%s punches %s's shoulder.","%s ударяет %s в плечо."},
},
["purrs"]={
{"%s purrs like a kitten.","%s мурлычет, как котенок."},
{"%s purrs at you.","%s мурлычет вам."},
{"%s purrs at %s.","%s мурлычет %s."},
},
["puts"]={
{"%s puts out a challenge to everyone. Bring it on!","%s бросает вызов всем. Вперед!"},
{"%s puts his arm around your shoulder.","%s обнимает вас за плечи."},
{"%s puts her arm around your shoulder.","%s обнимает вас за плечи."},
{"%s puts up his hand for a high five.","%s поднимает руку для дружеского приветствия."},
{"%s puts up her hand for a high five.","%s поднимает руку для дружеского приветствия."},
{"%s puts on the charm.","%s призывает на помощь весь свой шарм."},
{"%s puts his arm around %s's shoulder.","%s обнимает %s за плечи."},
{"%s puts her arm around %s's shoulder.","%s обнимает %s за плечи."},
},
["puzzled"]={
{"%s puzzled by you. What are you doing?","%s недоумевает. Что вы делаете?"},
},
["questions"]={
{"%s questions you.","%s спрашивает вас."},
{"%s questions %s.","%s спрашивает %s."},
},
["quietly"]={
{"%s quietly snickers to himself.","%s молча давится от смеха."},
{"%s quietly snickers to herself.","%s молча давится от смеха."},
},
["raises"]={
{"%s raises a drink in the air before chugging it down.  Cheers!","%s поднимает кубок. Будем здоровы!"},
{"%s raises a drink in the air before chugging it down.  Cheres!","%s поднимает кубок. Будем здоровы!"},
{"%s raises his eyebrow inquisitively at you.","%s поднимает бровь и вопросительно смотрит на вас."},
{"%s raises her eyebrow inquisitively at you.","%s смотрит на вас, вопросительно подняв бровь."},
{"%s raises his eyebrow inquisitively.","%s вопросительно поднимает бровь."},
{"%s raises her eyebrow inquisitively.","%s вопросительно поднимает бровь."},
{"%s raises his fist in anger at you.","%s в гневе замахивается на вас кулаком."},
{"%s raises her fist in anger at you.","%s в гневе замахивается на вас кулаком."},
{"%s raises a drink to you.  Cheers!","%s пьет за вас. Ваше здорорвье!"},
{"%s raises a drink to you. Cheers!","%s пьет за вас. Будем здоровы!"},
{"%s raises his hand in the air.","%s поднимает руку."},
{"%s raises her hand in the air.","%s поднимает руку."},
{"%s raises his fist in anger.","%s в гневе заносит кулак."},
{"%s raises her fist in anger.","%s в гневе заносит кулак."},
{"%s raises his eyebrow inquisitively at %s.","%s вопросительно поднимает бровь и смотрит на %s."},
{"%s raises her eyebrow inquisitively at %s.","%s поднимает бровь и вопросительно смотрит на %s."},
{"%s raises his fist in anger at %s.","%s в гневе замахивается кулаком на %s."},
{"%s raises her fist in anger at %s.","%s в гневе замахивается на %s."},
{"%s raises a drink to %s.  Cheers!","%s пьет за %s. Ваше здоровье!"},
},
["reached"]={
{"%s reached a new level. DING!","%s достигает нового уровня. ДЗИНЬ!"},
},
["remains"]={
{"%s remains calm.","%s сохраняет спокойствие."},
},
["roars"]={
{"%s roars with bestial vigor at you.  So fierce!","%s бешено рычит на вас. Какая ярость!"},
{"%s roars with bestial vigor.  So fierce!","%s бешено рычит. Вот это ярость!"},
{"%s roars with bestial vigor at %s.  So fierce!","%s бешено рычит на %s. Вот это ярость!"},
},
["rolls"]={
{"%s rolls on the floor laughing at you.","%s катается по полу от смеха при виде вас."},
{"%s rolls on the floor laughing.","%s катается по полу от смеха."},
{"%s rolls his eyes at you.","%s смотрит на вас и закатывает глаза."},
{"%s rolls her eyes at you.","%s смотрит на вас и закатывает глаза."},
{"%s rolls his eyes.","%s закатывает глаза."},
{"%s rolls her eyes.","%s закатывает глаза."},
{"%s rolls on the floor laughing at %s.","%s катается от смеха по полу, глядя на %s."},
{"%s rolls his eyes at %s.","%s смотрите на %s и закатываете глаза."},
{"%s rolls her eyes at %s.","%s смотрит на %s и закатывает глаза."},
},
["ruffles"]={
{"%s ruffles your hair.","%s взъерошивает вам волосы."},
{"%s ruffles his hair.","%s взъерошивает свои волосы."},
{"%s ruffles her hair.","%s взъерошивает свои волосы."},
{"%s ruffles %s's hair.","%s взъерошивает 3-2(%s) волосы."},
},
["runs"]={
{"%s runs around in a frenzied state of panic.","%s бегает кругами в паническом ужасе."},
},
["salutes"]={
{"%s salutes you with respect.","%s почтительно отдает вам честь."},
{"%s salutes %s with respect.","%s отдает честь %s."},
},
["says"]={
{"%s says a prayer for you.","%s молится за вас."},
{"%s says a prayer for %s.","%s молится за %s."},
},
["scoffs"]={
{"%s scoffs at you.","%s насмехается над вами."},
{"%s scoffs.","%s усмехается."},
{"%s scoffs at %s.","%s насмехается над %s."},
},
["scolds"]={
{"%s scolds himself.","%s бранит себя."},
{"%s scolds herself.","%s бранит себя."},
{"%s scolds you.","%s бранит вас."},
{"%s scolds %s.","%s бранит %s."},
},
["scowls"]={
{"%s scowls at you.","%s хмуро смотрит на вас."},
{"%s scowls.","%s хмурится."},
{"%s scowls at %s.","%s хмуро смотрит на %s."},
},
["scratches"]={
{"%s scratches himself.  Ah, much better!","%s чешется. Полегчало!"},
{"%s scratches herself.  Ah, much better!","%s чешется. Ну вот, теперь гораздо лучше."},
{"%s scratches you.  How catty!","%s чешет вас. Как котяво!"},
{"%s scratches %s.  How catty!","%s чешет %s. Как котяво!"},
},
["searches"]={
{"%s searches you for something.","%s осматривает вас в поисках чего-то."},
{"%s searches for something.","%s что-то ищет."},
{"%s searches %s for something.","%s осматривает %s в поисках чего-то."},
},
["serenades"]={
{"%s serenades you with a song.","%s поет вам серенаду."},
{"%s serenades %s with a song.","%s поет %s серенаду."},
},
["shakes"]={
{"%s shakes his rear at you.","%s вертит задом перед вами."},
{"%s shakes her rear at you.","%s вертит задом перед вами."},
{"%s shakes his fist at you.","%s грозит вам кулаком."},
{"%s shakes her fist at you.","%s грозит вам кулаком."},
{"%s shakes his rear.","%s вертит задом."},
{"%s shakes her rear.","%s вертит задом."},
{"%s shakes his fist.","%s потрясает кулаком."},
{"%s shakes her fist.","%s потрясает кулаком."},
{"%s shakes his rear at %s.","%s вертит задом перед %s."},
{"%s shakes her rear at %s.","%s вертит задом перед %s."},
{"%s shakes his fist at %s.","%s грозит %s кулаком."},
{"%s shakes her fist at %s.","%s грозит %s кулаком."},
},
["shimmies"]={
{"%s shimmies before the masses.","%s танцует перед толпой."},
{"%s shimmies before you.","%s танцует перед вами."},
{"%s shimmies before %s.","%s танцует перед %s."},
},
["shivers"]={
{"%s shivers in his boots. Chilling!","%s зябко дрожит. Холодно!"},
{"%s shivers in her boots. Chilling!","%s зябко дрожит. Холодно!"},
{"%s shivers beside you. Chilling!","%s дрожит у вас под боком. Холодно!"},
{"%s shivers beside %s. Chilling!","%s дрожит под боком у %s. Холодно!"},
},
["shoos"]={
{"%s shoos you away. Be gone pest!","%s отгоняет вас. Сгинь, зараза!"},
{"%s shoos the measly pests away.","%s отгоняет мерзких тварей."},
{"%s shoos %s away. Be gone pest!","%s отгоняет %s. Сгинь, зараза!"},
},
["shouts"]={
{"%s shouts at you.","%s кричит на вас."},
{"%s shouts.","%s кричит."},
{"%s shouts at %s.","%s кричит на %s."},
},
["shrugs"]={
{"%s shrugs at you.  Who knows?","%s пожимает плечами. Кто знает?"},
{"%s shrugs.  Who knows?","%s пожимает плечами. Кто знает?"},
{"%s shrugs at %s.  Who knows?","%s пожимает плечами в ответ %s. Кто знает?"},
},
["shudders"]={
{"%s shudders at the sight of you.","%s бросает в дрожь при виде вас."},
{"%s shudders.","%s бросает в дрожь."},
{"%s shudders at the sight of %s.","%s бросает в дрожь при виде %s."},
},
["sighs"]={
{"%s sighs at you.","%s вздыхает, глядя на вас."},
{"%s sighs at %s.","%s вздыхает, глядя на %s."},
},
["slaps"]={
{"%s slaps himself across the face. Ouch!","%s бьет себя по лицу. Ой!"},
{"%s slaps herself across the face. Ouch!","%s бьет себя по лицу. Ой!"},
{"%s slaps you across the face. Ouch!","%s дает вам пощечину. Ой!"},
{"%s slaps %s across the face. Ouch!","%s дает пощечину %s. Ох!"},
},
["smacks"]={
{"%s smacks you upside the head.","%s хлопает вас по макушке."},
{"%s smacks his forehead.","%s хлопает себя по лбу."},
{"%s smacks her forehead.","%s хлопает себя по лбу."},
{"%s smacks %s upside the head.","%s шлепает %s по макушке."},
},
["smells"]={
{"%s smells the air around him. Wow, someone stinks!","%s нюхает воздух. Ууу, чем это воняет?!"},
{"%s smells the air around her. Wow, someone stinks!","%s принюхивается. Ууу, чем это воняет?!"},
{"%s smells you. Wow, someone stinks!","%s чует вас. А это еще что за вонь?!"},
{"%s smells %s. Wow, someone stinks!","%s обнюхивает %s. Ууу, чем это воняет?!"},
},
["smiles"]={
{"%s smiles shyly at you.","%s застенчиво улыбается вам."},
{"%s smiles at you.","%s улыбается вам."},
{"%s smiles shyly.","%s смущенно улыбается."},
{"%s smiles.","%s улыбается."},
{"%s smiles shyly at %s.","%s застенчиво улыбается %s."},
{"%s smiles at %s.","%s улыбается %s."},
},
["smirks"]={
{"%s smirks slyly at you.","%s хитро улыбается вам."},
{"%s smirks slyly at %s.","%s хитро улыбается %s."},
},
["snaps"]={
{"%s snaps his fingers at you.","%s щелкает пальцами, обращаясь к вам."},
{"%s snaps her fingers at you.","%s щелкает пальцами, обращаясь к вам."},
{"%s snaps his fingers.","%s щелкает пальцами."},
{"%s snaps her fingers.","%s щелкает пальцами."},
{"%s snaps his fingers at %s.","%s щелкает пальцами, обращаясь к %s."},
{"%s snaps her fingers at %s.","%s щелкает пальцами, обращаясь к %s."},
},
["sneezes"]={
{"%s sneezes on you. Achoo!","%s чихает на вас. Апчхи!"},
{"%s sneezes. Achoo!","%s чихает. Апчхи!"},
{"%s sneezes on %s. Achoo!","%s чихает на %s. Апчхи!"},
},
["snickers"]={
{"%s snickers at you.","%s смеется про себя над вами."},
{"%s snickers at %s.","%s давится от смеха, глядя на %s."},
},
["sniffs"]={
{"%s sniffs the air around him.","%s нюхает воздух."},
{"%s sniffs the air around her.","%s нюхает вохдух."},
{"%s sniffs you.","%s обнюхивает вас."},
{"%s sniffs %s.","%s обнюхивает %s."},
},
["snorts"]={
{"%s snorts derisively at you.","%s презрительно фыркает на вас."},
{"%s snorts.","%s фыркает."},
{"%s snorts derisively at %s.","%s презрительно фыркает на %s."},
},
["snubs"]={
{"%s snubs all of the lowly peons around him.","%s пренебрежительно выговаривает окружающим его плебеям."},
{"%s snubs all of the lowly peons around her.","%s пренебрежительно выговаривает окружающим ее плебеям."},
{"%s snubs you.","%s бранит вас."},
{"%s snubs %s.","%s бранит %s."},
},
["soothes"]={
{"%s soothes you. There, there...things will be ok.","%s утешает вас. Ну-ну, все будет хорошо..."},
{"%s soothes %s. There, there...things will be ok.","%s утешает %s. Ну-ну, все будет хорошо..."},
},
["spits"]={
{"%s spits on the ground.","%s плюет на землю."},
{"%s spits on you.","%s плюет в вас."},
{"%s spits on %s.","%s плюет в %s."},
},
["squeals"]={
{"%s squeals like a pig.","%s визжит как свинья."},
{"%s squeals at you.","%s визжит при виде вас."},
{"%s squeals at %s.","%s визжит при виде %s."},
},
["stands"]={
{"%s stands at attention and salutes.","%s становится навытяжку и отдает честь."},
},
["stares"]={
{"%s stares blankly at his surroundings.","%s бессмысленно таращится по сторонам."},
{"%s stares blankly at her surroundings.","%s бессмысленно таращится по сторонам."},
{"%s stares off into the distance.","%s смотрит куда-то вдаль."},
{"%s stares blankly at you.","%s бессмысленно таращится на вас."},
{"%s stares at you in awe.","%s смотрит на вас с благоговейным трепетом."},
{"%s stares you down.","%s меряет вас взглядом."},
{"%s stares blankly at %s.","%s бессмысленно таращится на %s."},
{"%s stares at %s in awe.","%s смотрит на %s с благоговейным трепетом."},
{"%s stares %s down.","%s меряет взглядом %s."},
},
["starts"]={
{"%s starts to charge.","%s идет в атаку."},
},
["stretches"]={
{"%s stretches his arms out.","%s потягивается, разминая плечи."},
{"%s stretches her arms out.","%s потягивается, разминая плечи."},
},
["surrenders"]={
{"%s surrenders before you.  Such is the agony of defeat...","%s сдается вам. Тяжела горечь поражения..."},
{"%s surrenders to his opponents.","%s сдается на милость победителей."},
{"%s surrenders to her opponents.","%s сдается на милость победителей."},
{"%s surrenders before %s.  Such is the agony of defeat...","%s сдается %s. Тяжела горечь поражения..."},
},
["sweats"]={
{"%s sweats at the sight of you.","%s покрывается потом при виде вас."},
{"%s sweats at the sight of %s.","%s покрывается потом при виде %s."},
},
["takes"]={
{"%s takes one look at you and lets out a guffaw!","%s смотрит на вас и громко ржет!"},
{"%s takes a mighty quaff of his beverage.","%s одним глотком осушает свою кружку."},
{"%s takes a mighty quaff of her beverage.","%s одним глотком осушает свою кружку."},
{"%s takes one look at you and panics.","%s бросает на вас взгляд и впадает в панику."},
{"%s takes a deep breath.","%s глубоко вздыхает."},
{"%s takes one look at %s and lets out a guffaw!","%s смотрит на %s и ржет во весь голос!"},
{"%s takes one look at %s and panics.","%s бросает взгляд на %s и впадает в панику."},
},
["talks"]={
{"%s talks to himself since no one else seems interested.","%s разговаривает сам с собой. Остальным неинтересно..."},
{"%s talks to herself since no one else seems interested.","%s разговаривает сама с собой, поскольку остальные не слушают."},
{"%s talks excitedly with everyone.","%s возбужденно разговаривает со всеми вокруг."},
{"%s talks excitedly with you.","%s возбужденно разговаривает с вами."},
{"%s talks excitedly with %s.","%s оживленно разговаривает с %s."},
},
["taps"]={
{"%s taps her foot as she waits for you.","%s притопывает ногой в ожидании вас."},
{"%s taps his foot as he waits for you.","%s притопывает ногой в ожидании вас."},
{"%s taps his foot.  Hurry up already!","%s притопывает ногой. Ну, побыстрее!"},
{"%s taps her foot.  Hurry up already!","%s притопывает ногой. Ну побыстрее!"},
{"%s taps her foot as she waits for %s.","%s притопывает ногой в ожидании %s."},
{"%s taps his foot as he waits for %s.","%s притопывает ногой в ожидании %s."},
},
["taunts"]={
{"%s taunts everyone around him. Bring it fools!","%s глумливо поддразнивает всех вокруг. Ну, давайте, дураки!"},
{"%s taunts everyone around her. Bring it fools!","%s глумливо поддразнивает всех. Давайте, дураки!"},
},
["teases"]={
{"%s teases you.","%s дразнит вас."},
{"%s teases %s.","%s дразнит %s."},
},
["tells"]={
{"%s tells you NO.  Not going to happen.","%s говорит вам: \"НЕТ. Этому не бывать!\""},
{"%s tells you that she must be going.","%s говорит вам, что ей пора уходить."},
{"%s tells everyone to be quiet. Shhh!","%s велит всем помолчать. Тссс!"},
{"%s tells everyone to stop attacking.","%s велит все прекратить атаку."},
{"%s tells you to take a deep breath.","%s велит вам сделать глубокий вдох."},
{"%s tells you that he must be going.","%s говорит, что ему пора уходить."},
{"%s tells you to attack something.","%s велит вам атаковать кого-нибудь."},
{"%s tells everyone to attack you.","%s велит всем атаковать вас."},
{"%s tells you to be quiet. Shhh!","%s велит вам помолчать. Тссс!"},
{"%s tells you to stop attacking.","%s велит вам прекратить атаку."},
{"%s tells you to hurry up.","%s говорит вам поторопиться."},
{"%s tells everyone to go.","%s велит всем идти."},
{"%s tells you a joke.","%s рассказывает вам анекдот."},
{"%s tells you to go.","%s велит вам уйти."},
{"%s tells a joke.","%s рассказывает анекдот."},
{"%s tells %s NO.  Not going to happen.","%s говорит %s: \"НЕТ! Этому не бывать!\""},
{"%s tells %s that she must be going.","%s говорит %s, что ей пора уходить."},
{"%s tells %s to take a deep breath.","%s велит %s сделать глубокий вдох."},
{"%s tells %s that he must be going.","%s говорит %s, что ему пора уходить."},
{"%s tells %s to be quiet. Shhh!","%s велит 3-2(%s) помолчать. Тссс!"},
{"%s tells %s to stop attacking.","%s велит %s прекратить атаку."},
{"%s tells you to attack %s.","%s велит вам атаковать %s."},
{"%s tells %s to hurry up.","%s велит %s поторопиться."},
{"%s tells a joke to %s.","%s рассказывает анекдот %s."},
{"%s tells %s to go.","%s велит %s идти."},
},
["thanks"]={
{"%s thanks everyone.","%s благодарит всех."},
{"%s thanks you.","%s благодарит вас."},
{"%s thanks %s.","%s благодарит %s."},
},
["thinks"]={
{"%s thinks everyone around him is a son of a motherless ogre.","%s думает, что все вокруг него – отродья пьяного огра."},
{"%s thinks everyone around her is a son of a motherless ogre.","%s думает, что все вокруг – отродья пьяного огра."},
{"%s thinks you are the son of a motherless ogre.","%s думает, что вы – отродье пьяного огра."},
{"%s thinks this is serious business.","%s думает, что это нешуточное дело."},
{"%s thinks that you will regret it.","%s считает, что вы об этом пожалеете."},
{"%s thinks you are a sexy devil.","%s думает, что вы – сама сексуальность."},
{"%s thinks you are serious.","%s думает, что вы не шутите."},
{"%s thinks you have failed.","%s кажется, что вас постигла неудача."},
{"%s thinks you're charming.","Вы очаровали %s."},
{"%s thinks about you.","%s думает о вас."},
{"%s thinks %s is the son of a motherless ogre.","%s думает, что %s – отродье пьяного огра."},
{"%s thinks that %s will regret it.","%s уверен, что %s пожалеет об этом."},
{"%s thinks %s is a sexy devil.","%s считает, что %s – сама сексуальность."},
{"%s thinks %s is charming.","%s очарован %s."},
{"%s thinks %s is serious.","%s думает, что %s не шутит."},
{"%s thinks %s has failed.","%s кажется, что %s постигла неудача."},
{"%s thinks about %s.","%s думает о %s."},
},
["threatens"]={
{"%s threatens everyone with the wrath of doom.","%s пророчит всем кару небесную."},
{"%s threatens you with the wrath of doom.","%s пророчит вам кару небесную."},
{"%s threatens %s with the wrath of doom.","%s угрожает %s гневом судьбы."},
},
["tickles"]={
{"%s tickles you.  Hee hee!","%s щекочет вас. Хи-хи!"},
{"%s tickles %s.  Hee hee!","%s щекочет %s. Хи-хи!"},
},
["tries"]={
{"%s tries to sneak away from you.","%s пытается скрыться от вас."},
{"%s tries to pick up the pace.","%s пытается не отставать."},
{"%s tries to calm you down.","%s пытается вас успокоить."},
{"%s tries to sneak away.","%s пытается скрыться."},
{"%s tries to sneak away from %s.","%s пытается ускользнуть от %s."},
{"%s tries to calm %s down.","%s пытается успокоить %s."},
},
["twiddles"]={
{"%s twiddles his thumbs.","%s делает одобрительный жест."},
{"%s twiddles her thumbs.","%s делает одобрительный жест."},
},
["vetoes"]={
{"%s vetoes the motion on the floor.","%s запрещает всем двигаться."},
{"%s vetoes your motion.","%s запрещает вам двигаться."},
{"%s vetoes %s's motion.","%s запрещает %s двигаться."},
},
["vows"]={
{"%s vows she will have her revenge.","%s дает клятву отомстить."},
{"%s vows he will have his revenge.","%s дает клятву отомстить."},
{"%s vows revenge on you.","%s клянется отомстить вам."},
{"%s vows revenge on %s.","%s клянется отомстить %s."},
},
["wants"]={
{"%s wants you to know that she is hopelessly lost.","%s хочет показать вам, что она в полной растерянности."},
{"%s wants you to know that he is hopelessly lost.","%s хочет показать вам, что он в полной растерянности."},
{"%s wants to talk things over with you.","%s хочет обсудить ситуацию с вами."},
{"%s wants to know the meaning of life.","%s хочет познать смысл жизни."},
{"%s wants to be tickled.  Hee hee!","%s желает щекотки. Хи-хи!"},
{"%s wants to make an offer.","%s хочет внести предложение."},
{"%s wants %s to know that she is hopelessly lost.","%s хочет объяснить %s, что она в полном недоумении."},
{"%s wants %s to know that he is hopelessly lost.","%s хочет показать %s, что он в полном недоумении."},
{"%s wants to talk things over with %s.","%s хочет поговорить о делах с %s."},
},
["warns"]={
{"%s warns everyone that an enemy is near.","%s предупреждает всех, что враг близко."},
{"%s warns everyone of incoming enemies!","%s кричит, что враги идут!"},
{"%s warns you that an enemy is near.","%s предупреждает вас, что враг близко."},
{"%s warns everyone.","%s предостерегает всех."},
{"%s warns you.","%s предостерегает вас."},
{"%s warns %s that an enemy is near.","%s предупреждает %s что враг близко."},
{"%s warns %s.","%s предостерегает %s."},
},
["was"]={
{"%s was happy to help you.","%s говорит, что всегда с радостью придет вам на помощь."},
{"%s was happy to help.","%s говорит, что всегда с радостью придет на помощь."},
{"%s was just kidding!","%s просто шутит!"},
{"%s was happy to help %s.","%s говорит, что всегда с радостью придет на помощь %s."},
},
["waves"]={
{"%s waves goodbye to everyone.  Farewell!","%s машет рукой всем на прощание. До свидания!"},
{"%s waves goodbye to you.  Farewell!","%s машет вам рукой на прощание."},
{"%s waves at you.","%s машет вам рукой."},
{"%s waves.","%s машет рукой."},
{"%s waves goodbye to %s.  Farewell!","%s машет на прощание %s. До свидания!"},
{"%s waves at %s.","%s машет рукой %s."},
},
["welcomes"]={
{"%s welcomes everyone.","%s уверяет всех, что это был сущий пустяк."},
{"%s welcomes you.","%s приветствует вас."},
{"%s welcomes %s.","%s приветствует %s."},
},
["whines"]={
{"%s whines pathetically at you.","%s жалобно скулит перед вами."},
{"%s whines pathetically.","%s жалобно скулит."},
{"%s whines pathetically at %s.","%s жалобно скулит перед %s."},
},
["whistles"]={
{"%s whistles at you.","%s свистит вам."},
{"%s whistles at %s.","%s свистит %s."},
},
["will"]={
{"%s will be right back.  Sit tight.","%s сейчас вернется. Держитесь!"},
{"%s will be right back.","%s сейчас вернется."},
{"%s will be right back.  Sit tight, %s.","%s сейчас вернется. Держись, %s!"},
},
["winks"]={
{"%s winks slyly at you.","%s хитро подмигивает вам."},
{"%s winks slyly.","%s хитро подмигивает."},
{"%s winks slyly at %s.","%s хитро подмигивает %s."},
},
["wishes"]={
{"%s wishes someone would hold his hand.","%s хочется поздороваться с кем-то за руку."},
{"%s wishes someone would hold her hand.","%s хочется поздороваться с кем-то за руку."},
{"%s wishes you the best of luck.","%s желает вам удачи."},
{"%s wishes for some good luck.","%s желает хоть немного удачи."},
{"%s wishes everyone good luck.","%s желает окружающим удачи."},
{"%s wishes you good luck.","%s желает вам удачи."},
{"%s wishes %s the best of luck.","%s желает %s удачи."},
{"%s wishes %s good luck.","%s желает %s удачи."},
},
["with"]={
{"With arms flapping, %s struts around you.  Cluck, Cluck, Chicken!","Хлопая руками, %s расхаживает вокруг вас. Цыпа-цыпа-цыпа!"},
{"With arms flapping, you strut around %s.  Cluck, Cluck, Chicken!","Хлопая руками, вы расхаживаете вокруг %s. Цыпа-цыпа-цыпа!"},
{"With arms flapping, %s struts around.  Cluck, Cluck, Chicken!","Хлопая руками, %s расхаживает вокруг. Цыпа-цыпа-цыпа!"},
{"With arms flapping, %s struts around %s.  Cluck, Cluck, Chicken!","Хлопая руками, %s расхаживает вокруг %s. Цыпа-цыпа-цыпа!"},
},
["works"]={
{"%s works with you.","%s работает с вами."},
{"%s works with %s.","%s работает с %s."},
},
["yawns"]={
{"%s yawns sleepily at you.","%s лениво зевает вам в лицо."},
{"%s yawns sleepily.","%s сонно зевает."},
{"%s yawns sleepily at %s.","%s сонно зевает, глядя на %s."},
},
["yells"]={
{"%s yells for everyone to flee!","%s кричит, чтобы все убегали!"},
{"%s yells for you to flee!","%s кричит, чтобы вы убегали!"},
{"%s yells for %s to flee!","%s кричит %s: \"Беги!\""},
},
["you"]={
{"You surrender before %s.  Such is the agony of defeat...","Вы сдаетесь %s. Тяжела горечь поражения..."},
{"You are so bashful...too bashful to get %s's attention.","Вы слишком застенчивы, чтобы привлечь внимание %s."},
{"You look at %s and cover your face with your palm.","Вы смотрите на %s и прячете лицо в ладонях."},
{"You attempt to make %s an offer they can't refuse.","Вы делаете %s предложение, от которого невозможно отказаться."},
{"You want %s to know that you are hopelessly lost.","Вы хотите показать %s, что вы в полной растерянности."},
{"You soothe %s. There, there...things will be ok.","Вы утешаете %s. Ну-ну, все будет хорошо..."},
{"You let %s know you are thirsty. Spare a drink?","Вы показываетете %s, что хотите пить. Дадите глоточек?"},
{"You roar with bestial vigor at %s.  So fierce!","Вы в бешенстве рычите на %s. Вот это ярость!"},
{"You grovel before %s like a subservient peon.","Вы ползаете перед %s, как услужливый слуга."},
{"You take one look at %s and let out a guffaw!","Вы смотрите на %s и ржете!"},
{"You think %s is the son of a motherless ogre.","Вы думаете, что %s – отродье пьяного огра."},
{"You crack your knuckles while staring at %s.","Вы похрустываете костяшками, глядя на %s."},
{"You fidget impatiently while waiting for %s.","Вы нервничаете, ожидая %s."},
{"You make a taunting gesture at %s. Bring it!","Вы глумливо поддразниваете %s. Ну, давай!"},
{"You play the world's smallest violin for %s.","Вы играете на маленькой скрипочке для %s."},
{"You are getting a headache from %s's antics.","У вас болит голова от кривляний %s."},
{"You let %s know that you were just kidding!","Вы показываете %s, что это просто шутка!"},
{"You raise your eyebrow inquisitively at %s.","Вы вопросительно поднимаете бровь и смотрите на %s."},
{"You encourage %s to chug. CHUG! CHUG! CHUG!","Вы подначиваете %s пить до дна. ПЕЙ ДО ДНА!"},
{"You are hungry.  Maybe %s has some food...","Вы голодны. Возможно, у %s есть что-нибудь поесть..."},
{"You bask in the glory of victory with %s.","Вы упиваетесь славой вместе с %s."},
{"You congratulate %s on a new level. DING!","Вы поздравляете %s с новым уровнем. ДЗИНЬ!"},
{"You brush up against %s and fart loudly.","Вы третесь об %s и громко испускаете газы."},
{"You brandish your weapon fiercely at %s.","Вы яростно замахиваетесь своим оружием на %s."},
{"You threaten %s with the wrath of doom.","Вы пророчите %s кару небесную."},
{"You bounce up and down in front of %s.","Вы прыгаете на месте перед %s."},
{"You point out %s as an incoming enemy!","Вы указываете на %s как на врага!"},
{"You put your arm around %s's shoulder.","Вы обнимаете %s за плечи."},
{"You let %s know you'll be right back.","Вы показываете %s, что сейчас вернетесь."},
{"You cower in fear at the sight of %s.","Вы дрожите от страха при виде %s."},
{"You tell %s NO.  Not going to happen.","Вы отвечаете %s: \"НЕТ! Этому не бывать!\""},
{"You pick your nose and show it to %s.","Вы достаете из носу козявку и показываете ее %s."},
{"You roll on the floor laughing at %s.","Вы катаетесь от смеха по полу, глядя на %s."},
{"You want to talk things over with %s.","Вы хотите обсудить дела с %s."},
{"You tap your foot as you wait for %s.","Вы притопываете ногой в ожидании %s."},
{"You clap for %s, clearly unimpressed.","Вы подчеркнуто равнодушно аплодируете %s."},
{"You look at %s with a confused look.","Вы недоуменно смотрите на %s."},
{"You frown with disappointment at %s.","Вы хмуро смотрите на %s."},
{"You bare your teeth and snarl at %s.","Вы скалитесь и ворчите на %s."},
{"You flop about helplessly around %s.","Вы беспомощно суетитесь вокруг %s."},
{"You raise your fist in anger at %s.","Вы в гневе замахиваетесь кулаком на %s."},
{"You drop your trousers and moon %s.","Вы снимаете штаны и показываете зад %s."},
{"You let %s know that you are tired.","Вы показываете %s, что устали."},
{"You look at %s and raise your hand.","Вы смотрите на %s и поднимаете руку."},
{"You let %s know that you are ready!","Вы показываете %s, что вы готовы!"},
{"You tell %s that you must be going.","Вы говорите %s, что вам пора уходить."},
{"You wave goodbye to %s.  Farewell!","Вы машете рукой %s. До свидания!"},
{"You look at %s and begin to drool.","Вы млеете, глядя на %s."},
{"You flex at %s.  Oooooh so strong!","Вы поигрываете мускулами перед %s. Какая сила!"},
{"You take one look at %s and panic.","Вы бросаете взгляд на %s и впадаете в панику."},
{"You are surprised by %s's actions.","Вы удивлены действиями %s."},
{"You let %s know that you are cold.","Вы показываете %s, что вы замерзли."},
{"You slap %s across the face. Ouch!","Вы даете пощечину %s. Ох!"},
{"You smell %s. Wow, someone stinks!","Вы обнюхиваете %s. Ууу, чем это воняет?!"},
{"You commend %s on a job well done.","Вы хвалите %s за хорошую работу."},
{"You tell %s to take a deep breath.","Вы велите %s сделать глубокий вдох."},
{"You warn %s that an enemy is near.","Вы предупреждаете %s, что враг близко."},
{"You are curious what %s is up to.","Вам интересно, что будет делать %s."},
{"You raise a drink to %s.  Cheers!","Вы пьете за %s. Ваше здоровье!"},
{"You greet %s with a hearty hello!","Вы от всего сердца приветствуете %s!"},
{"You mutter angrily at %s. Hmmmph!","Вы зло бормочите, обращаясь к %s. Гхмммм!"},
{"You think that %s will regret it.","Вы уверены, что %s пожалеет об этом."},
{"You bonk %s on the noggin.  Doh!","Вы бьете %s по голове. Буммм!"},
{"You begin to eat in front of %s.","Вы начинаете есть на глазах у %s."},
{"You look down upon %s with pity.","Вы с жалостью взираете на %s."},
{"You check %s for a pulse. Oh no!","Вы проверяете, есть ли у %s пульс. О нет!"},
{"You have a bad feeling about %s.","У вас предчувствие, что %s сейчас все испортит."},
{"You cross your arms at %s. Hmph!","Вы скрещиваете руки, глядя на %s. Хм!"},
{"You are terribly bored with %s.","Общение с %s вас основательно утомило."},
{"You gloat over %s's misfortune.","Вы злорадствуете по поводу неудачи %s."},
{"You mock the foolishness of %s.","Вы смеетесь над глупостью %s."},
{"You shiver beside %s. Chilling!","Вы дрожите рядом с %s. Холодно!"},
{"You shoo %s away. Be gone pest!","Вы отгоняете %s. Сгинь, зараза!"},
{"You tell everyone to attack %s.","Вы велите всем атаковать %s."},
{"You shudder at the sight of %s.","Вас бросает в дрожь при виде %s."},
{"You make a rude gesture at %s.","Вы делаете неприличный жест в сторону %s."},
{"You tell %s to be quiet. Shhh!","Вы велите %s помолчать. Тссс!"},
{"You try to sneak away from %s.","Вы пытаетесь скрыться от %s"},
{"You tell %s to stop attacking.","Вы велите %s прекратить атаку."},
{"You burp rudely in %s's face.","Вы грубо рыгаете в лицо %s."},
{"You think %s is a sexy devil.","Вы думаете, что %s – сама сексуальность."},
{"You whine pathetically at %s.","Вы жалобно скулите перед %s."},
{"You introduce yourself to %s.","Вы представляетесь %s."},
{"You faint at the sight of %s.","Вы падаете в обморок при виде %s."},
{"You wish %s the best of luck.","Вы желаете %s удачи."},
{"You smack %s upside the head.","Вы хлопаете %s по макушке."},
{"You sweat at the sight of %s.","Вы покрываетесь потом при виде %s."},
{"You apologize to %s.  Sorry!","Вы извиняетесь перед %s. Прости!"},
{"You cackle maniacally at %s.","Вы глупо хохочете над %s."},
{"You moan suggestively at %s.","Вы призывно стонете перед %s."},
{"You shrug at %s.  Who knows?","Вы пожимаете плечами в ответ %s. Кто знает?"},
{"You moo at %s. Mooooooooooo.","Вы мычите на %s. Мууууууу!"},
{"You motion for %s to follow.","Вы жестом велите %s следовать за вами."},
{"You blame %s for everything.","Вы во всем вините %s."},
{"You plead with %s for mercy.","Вы просите %s о пощаде"},
{"You serenade %s with a song.","Вы поете %s серенаду."},
{"You snap your fingers at %s.","Вы щелкаете пальцами, обращаясь к %s"},
{"You search %s for something.","Вы осматриваете %s в поисках чего-то."},
{"You are very happy with %s!","Вы очень довольны %s!"},
{"You massage %s's shoulders.","Вы массируете плечи %s."},
{"You peer at %s searchingly.","Вы испытующе смотрите на %s."},
{"You salute %s with respect.","Вы почтительно отдаете честь %s."},
{"You scratch %s.  How catty!","Вы чешете %s. Как котяво!"},
{"You talk excitedly with %s.","Вы возбужденно разговариваете с %s."},
{"You growl menacingly at %s.","Вы угрожающе рычите на %s."},
{"You challenge %s to a duel.","Вы вызываете %s на дуэль."},
{"You snort derisively at %s.","Вы презрительно фыркаете на %s."},
{"You applaud at %s.  Bravo!","Вы рукоплещете %s. Браво!"},
{"You beg %s.  How pathetic.","Вы с мольбой смотрите на %s. Выглядит жалко."},
{"You clap excitedly for %s.","Вы восторженно апплодируете %s."},
{"You shake your rear at %s.","Вы вертите задом перед %s."},
{"You listen intently to %s.","Вы внимательно слушаете %s."},
{"You lavish praise upon %s.","Вы превозносите %s."},
{"You are embarrassed by %s.","Вы сбиты с толку %s."},
{"You shake your fist at %s.","Вы грозите %s кулаком."},
{"You give %s a shifty look.","Вы подозрительно поглядываете на %s."},
{"You were happy to help %s.","Вы были рады помочь %s."},
{"You cry on %s's shoulder.","Вы рыдаете на плече у %s."},
{"You gaze longingly at %s.","Вы пожираете взглядом %s."},
{"You look at %s and groan.","Вы смотрите на %s и стонете."},
{"You cuddle up against %s.","Вы прижимаетесь к %s."},
{"You look at %s nervously.","Вы обеспокоено смотрите на %s."},
{"You roll your eyes at %s.","Вы смотрите на %s и закатываете глаза."},
{"You are suspicious of %s.","Вы коситесь на %s с подозрением."},
{"You think %s is charming.","Вы очарованы %s."},
{"You cringe away from %s.","Вы в страхе пятитесь от %s."},
{"You glare angrily at %s.","Вы бросаете гневный взгляд на %s."},
{"You grin wickedly at %s.","Вы злобно ухмыляетесь %s."},
{"You say a prayer for %s.","Вы молитесь за %s."},
{"You yawn sleepily at %s.","Вы лениво зеваете, глядя на %s."},
{"You try to calm %s down.","Вы пытаетесь успокоить %s."},
{"You ponder %s's actions.","Вы обдумываете действия %s."},
{"You pounce on top of %s.","Вы бросаетесь на %s."},
{"You tickle %s.  Hee hee!","Вы щекочете %s. Хи-хи!"},
{"You yell for %s to flee!","Вы кричите %s: \"Беги!\""},
{"You think %s is serious.","Вы думаете, что %s не шутит."},
{"You stare blankly at %s.","Вы бессмысленно таращитесь на %s."},
{"You think %s has failed.","Вам кажется, что %s потерпел неудачу."},
{"You give %s a high five!","Вы по-дружески здороваетесь с %s!"},
{"You look at %s absently.","Вы смотрите на %s отсутствующим взглядом."},
{"You tell %s to hurry up.","Вы говорите %s поторопиться."},
{"You punch %s's shoulder.","Вы ударяете %s в плечо."},
{"You sneeze on %s. Achoo!","Вы чихаете на %s. Апчхи!"},
{"You eye %s up and down.","Вы меряете взглядом %s."},
{"You lie down before %s.","Вы ложитесь перед %s."},
{"You stare at %s in awe.","Вы смотрите на %s с благоговейным трепетом."},
{"You give %s the signal.","Вы подаете %s сигнал."},
{"You curtsey before %s.","Вы делаете реверанс перед %s."},
{"You blow a kiss to %s.","Вы посылаете воздушный поцелуй %s."},
{"You smile shyly at %s.","Вы застенчиво улыбаетесь %s."},
{"You are puzzled by %s.","Вы озадачены поведением %s."},
{"You smirk slyly at %s.","Вы хитро ухмыляетесь %s."},
{"You wish %s good luck.","Вы желаете %s удачи."},
{"You are jealous of %s.","Вы завидуете %s."},
{"You make %s a promise.","Вы даете %s обещание."},
{"You vow revenge on %s.","Вы клянетесь отомстить %s."},
{"You are amazed by %s!","Вы восхищены %s!"},
{"You shimmy before %s.","Вы танцуете перед %s."},
{"You veto %s's motion.","Вы запрещаете %s двигаться."},
{"You are scared of %s.","Вы пугаетесь %s."},
{"You wink slyly at %s.","Вы хитро подмигиваете %s."},
{"You disagree with %s.","Вы не согласны с %s."},
{"You ruffle %s's hair.","Вы взъерошиваете волосы %s."},
{"You offer %s a truce.","Вы предлагаете %s перемирие."},
{"You congratulate %s.","Вы поздравляете %s."},
{"You greet %s warmly.","Вы тепло приветствуете %s."},
{"You kneel before %s.","Вы преклоняете колена перед %s."},
{"You are proud of %s.","Вы гордитесь %s."},
{"You cover %s's ears.","Вы закрываете уши %s."},
{"You beckon %s over.","Вы жестом подзываете %s."},
{"You bite %s.  Ouch!","Вы кусаете %s. Ох!"},
{"You duck behind %s.","Вы прячетесь за спину %s."},
{"You ask %s to wait.","Вы просите %s подождать."},
{"You tell %s a joke.","Вы рассказываете анекдот %s."},
{"You hold %s's hand.","Вы держитесь с %s за руку."},
{"You think about %s.","Вы думаете о %s."},
{"You agree with %s.","Вы соглашаетесь с %s."},
{"You bow before %s.","Вы кланяетесь %s."},
{"You chuckle at %s.","Вы хихикаете над %s."},
{"You dance with %s.","Вы танцуете с %s."},
{"You plead with %s.","Вы умоляете %s."},
{"You poke %s.  Hey!","Вы пихаете в бок %s. Эй!"},
{"You stare %s down.","Вы меряете взглядом %s."},
{"You whistle at %s.","Вы свистите %s."},
{"You snicker at %s.","Вы давитесь от смеха, глядя на %s."},
{"You flirt with %s.","Вы флиртуете с %s."},
{"You gently pat %s.","Вы ласково гладите %s."},
{"You tell %s to go.","Вы велите %s уйти."},
{"You giggle at %s.","Вы хихикаете при виде %s."},
{"You work with %s.","Вы работаете с %s."},
{"You boggle at %s.","Вы изумленно смотрите на %s."},
{"You encourage %s.","Вы подбадриваете %s."},
{"You glower at %s.","Вы зло смотрите на %s."},
{"You squeal at %s.","Вы визжите при виде %s."},
{"You object to %s.","Вы возражаете %s."},
{"You blink at %s.","Вы моргаете, глядя на %s."},
{"You blush at %s.","Вы заливаетесь краской при виде %s."},
{"You cheer at %s.","Вы радуетесь успехам %s."},
{"You cough at %s.","Вы кашляете, привлекая внимание %s."},
{"You laugh at %s.","Вы смеетесь над %s."},
{"You point at %s.","Вы показываете на %s."},
{"You shout at %s.","Вы кричите на %s."},
{"You question %s.","Вы спрашиваете %s."},
{"You smile at %s.","Вы улыбаетесь %s."},
{"You scoff at %s.","Вы насмехаетесь над %s."},
{"You scowl at %s.","Вы хмуро смотрите на %s."},
{"You gasp at %s.","Вы ахаете при виде %s."},
{"You sigh at %s.","Вы вздыхаете, глядя на %s."},
{"You spit on %s.","Вы плюете в %s."},
{"You wave at %s.","Вы машете рукой %s."},
{"You welcome %s.","Вы приветствуете %s."},
{"You comfort %s.","Вы утешаете %s."},
{"You purr at %s.","Вы мурлычете %s."},
{"You bark at %s.","Вы рявкаете на %s."},
{"You hiss at %s.","Вы шипите на %s."},
{"You pout at %s.","Вы дуетесь на %s."},
{"You look at %s.","Вы смотрите на %s."},
{"You nod at %s.","Вы киваете %s."},
{"You thank %s.","Вы благодарите %s."},
{"You sniff %s.","Вы обнюхиваете %s."},
{"You tease %s.","Вы дразните %s."},
{"You doubt %s.","Вы сомневаетесь в %s."},
{"You pinch %s.","Вы щипаете %s."},
{"You scold %s.","Вы браните %s."},
{"You hail %s.","Вы приветствуете %s."},
{"You lick %s.","Вы облизываете %s."},
{"You snub %s.","Вы браните %s."},
{"You love %s.","Вы любите %s."},
{"You warn %s.","Вы предостерегаете %s."},
{"You hug %s.","Вы крепко обнимаете %s."},
{"You pet %s.","Вы поглаживаете %s."},
},
}
